### ISSUE TITLE
juju manual mode bootstrap

### ISSUE THREAD

**Issue by kharade-rohan** [juju/juju#10220]
While adding machine manually to cloud (type - manual); got error of machine manually provisioned. I used [this](https://askubuntu.com/questions/433842/how-to-resolve-error-machine-is-already-provisioned-in-manual-provision-set-up) to resolve but didn't worked. 

Then I tried to kill and add new controller but it stuck at following for very long time
```
Looking for packaged Juju agent version 2.6.2 for amd64
Installing Juju agent on bootstrap instance
Fetching Juju GUI 2.14.0
Running machine configuration script...
```
How to resolve this issue.
[Ubuntu 18.04 machine, node has active internet connection]

**Comment by timClicks** [comment]
Sorry to hear that you are having trouble @kharade-rohan. The best place to ask for help is our [forum](discourse.jujucharms.com/c/users)

I am closing the issue here, as our GitHub tracker is reserved for code review.
