### ISSUE TITLE
Subordinate charms are not displayed in `juju status`.

### ISSUE THREAD

**Issue by allomov** [juju/juju#1064]
Hey, all.

Is it ok that subordinate charms are not displayed in `juju status <charm-name>` while are they are not binded to service?

Let's take `logstash-agent` for instance. When you run `juju status` it shows `logstash-agent` service, but if you try to run `juju status logstash-agent` it will show you empty json hash if you didn't binded `logstash-agent` to other service. It can be confusing imo.

Also subordinate charms don't have autocompletion in ubuntu. 

I'm using Juju with following version: 1.21-alpha2-trusty-amd64.

**Comment by mattyw** [comment]
@allomov thanks for your report, and sorry for the late response. Your bug is being tracked here: https://bugs.launchpad.net/juju-core/+bug/1430943

**Comment by allomov** [comment]
I guess this issue can be closed since it is tracked on launchpad.
