### ISSUE TITLE
Can't remove credentials after removing associated cloud

### ISSUE THREAD

**Issue by LucidNeko** [juju/juju#11114]
If you `juju remove-cloud` before `juju remove-credential` it fails to remove the credential.

_(Raising here because ubuntu one sso isn't working on launchpad)_

$ juju remove-cloud openstack
This operation can be applied to both a copy on this client and to the one on a controller.
No current controller was detected but there are other controllers registered: use -c or --controller to specify a controller if needed.
Do you ONLY want to remove cloud openstack from this client? (Y/n):

Removed details of cloud "openstack" from the client
[~]$ juju remove-credential openstack evanh
This operation can be applied to both a copy on this client and to the one on a controller.
No current controller was detected but there are other controllers registered: use -c or --controller to specify a controller if needed.
Do you ONLY want to remove credential "evanh" for cloud "openstack" from this client? (Y/n):

ERROR cloud openstack not valid
No cloud "openstack" is found.
To view all available clouds, use 'juju clouds'.
To add new cloud, use 'juju add-cloud'.

**Comment by SimonRichardson** [comment]
@LucidNeko bugs are reported here (if can duplicate it there please) - https://bugs.launchpad.net/juju/+filebug

**Comment by anastasiamac** [comment]
Added to our tracking https://bugs.launchpad.net/juju/+bug/1862551
