### ISSUE TITLE
Make lxc.conf used extendable/customisable

### ISSUE THREAD

**Issue by OddBloke** [juju/juju#1112]
There are some situations where being able to modify the lxc config used to set up the containers for the local provider could be very handy; please consider providing some way of so doing.

The specific case I'm looking at is the Juju Vagrant images where we want all containers to have an APT proxy set up. The cleanest way to do this would be using lxc hooks to run a script which injects the cache, but we can't do that. As a result, we have to muck around with the templates, which is error-prone, brittle and adds to start-up time (as we have to have all the templates that we want to modify in-place at boot time, meaning we have to download all templates that there might be images for).

**Comment by anastasiamac** [comment]
Thank you for suggestion \o/

We track suggestions and issues on launchpad: https://bugs.launchpad.net/juju
I have filed this as a wishlist item: https://bugs.launchpad.net/juju/+bug/1615876
