### ISSUE TITLE
juju should not record ssh certificates of ephemeral hosts

### ISSUE THREAD

**Issue by achiang** [juju/juju#138]
1. juju bootstrap [openstack environment]
2. work with juju for a while
3. juju destroy-environment <openstack>
4. juju bootstrap [openstack]
5. possibly encounter big scary warning - http://pastebin.ubuntu.com/7675327/

If I issue: juju ssh <unit>, then juju should keep track of these ephemeral units and remove them from my environment upon destroy-environment, or better yet, not record them in the first place, using something like -O "UserKnownHostsFile /dev/null", e.g.

I will pre-emptively agree that juju can't do anything about the case where the user does a raw ssh to the unit, so in that case, let the user deal with it herself.

Besides being a scary warning, it also results in an actual usability issue. If the openstack environment is located behind a jump host, and you require sshuttle, e.g., to successfully use 'juju status', then...

6. juju status => failure

Because sshuttle will refuse to setup a tunnel whilst you still have the old key. You are required to issue:

$ ssh-keygen -f "/path/to/.ssh/known_hosts" -R <ip address>

Before sshuttle will succeed.

**Comment by anastasiamac** [comment]
According to the bug and proposal linked above, this issue has been resolved.
