### ISSUE TITLE
About OpenStack version and HA

### ISSUE THREAD

**Issue by jiasir** [juju/juju#1540]
If this procject supporint OpenStack HA environment? I want to deploy a Juno version and HA environment.  Can you recommend a way? Many thanks!

**Comment by anastasiamac** [comment]
Our documentation is at https://jujucharms.com/docs
You will need to bootstrap on Openstack and run the command to ensure availability. The exact wording and configuration of needed commands depends on what version of Juju you are using.
Should you encounter any issues, have concerns or suggestions, we track our bugs on launchpad on https://bugs.launchpad.net/juju-core/

**Comment by jiasir** [comment]
@anastasiamac Thanks!
