### ISSUE TITLE
Juju calls add-apt-repository without setting http_proxy

### ISSUE THREAD

**Issue by mthibaut** [juju/juju#1880]
# Description
juju bootstrap called by openstack-install doesn't set http_proxy in the environment when adding repositories using add-apt-repository.

This makes *any* installation fail where a proxy is required to reach outside hosts.

Upstream bug references:
* An old where add-apt-repository wouldn't work at all without a proxy. This one was fixed but gives a good rationale for fixing the real bug: https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/516032
* And the real bug, which is that add-apt-repository/apt-key don't honor Acquire::http::proxy from APT's configuration files: https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761

As upstream has not been convinced for 5+ years that this should even be fixed, I would like to request that this is fixed *thoroughly* in Juju until upstream is convinced.

# Proposed fix
The *best* fix IMO is to simply set the proxies inside /etc/environment for *all* shell processes. This would remove the need for Juju to even bother with proxies from then on, and it would solve an entire class of issues rather than fixing a single problem:

cat /etc/environment
...
http_proxy=http://192.168.1.1:3128/
FTP_PROXY=http://192.168.1.1:3128/
ftp_proxy=http://192.168.1.1:3128/
HTTPS_PROXY=http://192.168.1.1:3128/
https_proxy=http://192.168.1.1:3128/
no_proxy=127.0.0.1,localhost
HTTP_PROXY=http://192.168.1.1:3128/
...

Note that both upper and lower case need to be set, as some programs require the lower case ones and vice versa.

**Comment by mthibaut** [comment]
# Another proposed fix

If the proxies are already set in the environment by Juju, then the problem is that they are not surviving the sudo call. For security reasons sudo does not allow environment variables to be altered - think what could happen if people could set root's PATH when calling sudo :).

So to fix this you can set the following in /etc/sudoers.d/90-cloud-init-users:
```
Defaults env_keep += "http_proxy https_proxy ftp_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY no_proxy"
```

**Comment by anastasiamac** [comment]
Juju supports proxy for several versions. 
This is documentation from Juju 1.22: https://jujucharms.com/docs/1.22/howto-proxies 
Juju 2.0 documentation: https://jujucharms.com/docs/2.0/juju-misc
