### ISSUE TITLE
Can not install juju from "go install"

### ISSUE THREAD

**Issue by cloudtrends** [juju/juju#1904]
hi all,

Can not install juju from "go install"

I had already config golang env and go get juju from github to my local lab .

I can successfully run  following command,

1.  godeps -u dependencies.tsv
2.  make install-dependencies
3.  go test -v ./state -gocheck.v -gocheck.f="StateSuite|CleanupSuite"

But when I run ,
cd cd $GOPATH/src/github.com/juju/juju
go install -v github.com/juju/juju/

nothings happend , no errors , no juju binary file in GOPATH/bin  directory .

Is there something I missed ?

Thanks in advance.

**Comment by davecheney** [comment]
The command binaries are stored in a lower directory, use:


     go install -v github.com/juju/juju/...

**Comment by cloudtrends** [comment]
@davecheney   you save me .

I will close this issue . 

BTW:  the reason why I use juju by compile from source code , just because : 

http://askubuntu.com/questions/598994/cannot-get-juju-works-with-openstack-juno

thanks again.
