### ISSUE TITLE
cmd/juju: "error" capitalisation is inconsistent

### ISSUE THREAD

**Issue by rogpeppe** [juju/juju#2104]
The "error" prefix on output lines is different depending
on where the command fails.

For example:

    % juju deploy dsvgfdsavds
    ERROR cannot resolve charm URL "cs:trusty/dsvgfdsavds": charm not found
    % juju deploy
    error: no charm specified

**Comment by anastasiamac** [comment]
Roger
I have filed the bug in launchpad https://bugs.launchpad.net/juju-core/+bug/1614948
Since we track our bugs there, I'll close this issue to avoid miscommunication.
