### ISSUE TITLE
OpenStack Keystone v3 Authentication Support

### ISSUE THREAD

**Issue by llarsson** [juju/juju#2406]
Please start supporting OpenStack Keystone v3 Authentication API. It has been out for years, and it is time to support it in addition to v2, which is already in juju.

API examples using Curl:
http://docs.openstack.org/developer/keystone/api_curl_examples.html

**Comment by anastasiamac** [comment]
Juju 2.0 now supports OpenStack Keystone v3 Authentication API since 2.0-beta12.
For prompt replies and assistance, please report bugs or concerns on  https://bugs.launchpad.net/juju-core. We track Juju issues there.
