### ISSUE TITLE
Juju messing up preseed network after MAAS install

### ISSUE THREAD

**Issue by pieterk** [juju/juju#2433]
Using Juju in conjunction with MAAS when a node is deployed with a bonded network. The bonded network is initially setup correctly and works 100% however Juju when doing its thing afterwards messes with the config and breaks it so that the bond never works again. 

Example below. (localhost omitted)

After MAAS install but before Juju init (note, MAC is masked but is an actual MAC address on server)
```
auto p2p1
iface p2p1 inet manual
  bond-master bond0
  mtu 9000

auto p2p2
iface p2p2 inet manual
  bond-master bond0
  mtu 9000

auto bond0
iface bond0 inet dhcp
  bond-mode active-backup
  bond-miimon 100
  bond-slaves none
  hwaddress ether xx:xx:xx:xx:xx:xx
  up ifconfig bond0 mtu 9000
```

After Juju does its thing the network then looks like this.
```
auto eth0
iface eth0 inet manual
  bond-master bond0
  mtu 9000

auto eth1
iface eth1 inet manual
  bond-master bond0
  mtu 9000


  bond-mode active-backup
  bond-miimon 100
  bond-slaves none
  hwaddress ether xx:xx:xx:xx:xx:xx
  up ifconfig bond0 mtu 9000

# Primary interface (defining the default route)
iface bond0 inet manual

# Bridge to use for LXC/KVM containers
auto juju-br0
iface juju-br0 inet dhcp
  bridge_ports bond0
```

As you can see it renames the network adapters (not a problem) but then messes up the bonding configuration so the machine does not bond correctly. It should be a simple active-backup but checking the bond in /proc/net/bonding/bond0 it shows round-robin.

**Comment by martijn4evers** [comment]
I am running into something similar as well. In your case it shows round-robin because that is most likely the default. The bind-mode is probably not read because it is placed under eth1.

The code here explains why this is happening:
https://github.com/juju/juju/blob/juju-1.24.5/provider/maas/environ.go#L1119

I think 'setupJujuNetworking' should not change the primary interface. Instead it should only use it for the bridge (using 'bridge_ports bond0'). Also can anyone explain why the primary interface must not auto start? When auto start is disabled bond0 is not started (which stops the bridge from sending DHCP requests over the primary interface) not allowing ethernet traffic.

**Comment by martijn4evers** [comment]
Having read the [interfaces](http://manpages.ubuntu.com/manpages/trusty/man5/interfaces.5.html) and [bridge-util](http://manpages.ubuntu.com/manpages/trusty/man5/bridge-utils-interfaces.5.html) manuals. I found an other approach.

Essentially the bridge should take over the method and all the options from that method of the primary interface and add the 'bridge_ports' option (with maybe some additional bridge_* options if needed). Usually, if not always, the method and options are from the inet address family.

When implemented the bridge will be configured like the primary interface with all static, dhcp or other inet address family options correctly configured. Still any 'driver' specific options configured for the primary interface would still work, e.i. bonding options.

The only drawback from this approach would be the hard-coded list of inet address family methods and options.

**Comment by dimitern** [comment]
@martijn4evers I have a proposed (but yet untested, except manually) PR, which you could try and see if it resolves your issue - https://github.com/juju/juju/pull/3539

**Comment by anastasiamac** [comment]
We track our bugs and issues in launchpad - https://bugs.launchpad.net/juju-core
