### ISSUE TITLE
lsblk.go is complaining about in use loopback devices

### ISSUE THREAD

**Issue by cholcombe973** [juju/juju#2731]
I'm seeing this often in my logs because I have a loopback device in use by another process:

machine-12[1159]: 2015-07-07 20:09:41 ERROR juju.worker.diskmanager lsblk.go:115 error checking if "loop1" is in use: open /dev/loop1: operation not permitted

**Comment by anastasiamac** [comment]
Which version of Juju are using? Different providers support different storage types...
Also, we track our bugs and issues on launchpad - https://bugs.launchpad.net/juju-core. For faster resolution, please file bugs there.
