### ISSUE TITLE
juju debug-log is missing or broken?

### ISSUE THREAD

**Issue by cholcombe973** [juju/juju#2778]
I just upgraded to the latest release and it seems that debug-log no longer works.  Is this by accident?

```
juju debug-log
ERROR cannot open log file: open /var/log/juju-chris-local/all-machines.log: no such file or directory
```
I thought if i created this file it would start using it but it doesn't seem to be picking it up at all now.  I'm using ```tail /var/log/juju*/unit-*``` now in the mean time.

**Comment by anastasiamac** [comment]
Since the issue has been filed, we have move to a newer Juju version -1.25. Debug-log functionality has changed considerably since July last year and is still further improved in Juju 2.0.

If you are still experience this failure, please file a bug on launchpad https://bugs.launchpad.net/juju-core
