### ISSUE TITLE
Unable to generate config on OS X 10.11 (beta 3)

### ISSUE THREAD

**Issue by gAmUssA** [juju/juju#2912]
Hello,

Getting following error doing `juju generate-config`

Please, assist.

```
»  juju generate-config
panic: osVersion reported an error: unknown series ""

goroutine 1 [running]:
github.com/juju/juju/version.mustOSVersion(0x0, 0x0)
	/private/tmp/juju20150803-58782-smsivm/juju-core_1.24.2/src/github.com/juju/juju/version/osversion.go:26 +0xed
github.com/juju/juju/version.init()
	/private/tmp/juju20150803-58782-smsivm/juju-core_1.24.2/src/github.com/juju/juju/version/version.go:36 +0x478
github.com/juju/juju/tools.init()
	/private/tmp/juju20150803-58782-smsivm/juju-core_1.24.2/src/github.com/juju/juju/tools/tools.go:20 +0x54
main.init()
	/private/tmp/juju20150803-58782-smsivm/juju-core_1.24.2/src/github.com/juju/juju/cmd/juju/upgradejuju.go:417 +0x50

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by fenris** [comment]
$ juju status
panic: osVersion reported an error: unknown series ""

goroutine 1 [running]:
github.com/juju/juju/version.mustOSVersion(0x0, 0x0)
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/version/osversion.go:26 +0xfa
github.com/juju/juju/version.init()
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/version/version.go:36 +0x4ed
github.com/juju/juju/apiserver/params.init()
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/apiserver/params/usermanager.go:59 +0x58
github.com/juju/juju/api.init()
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/api/state.go:345 +0x51
github.com/juju/juju/cmd/envcmd.init()
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/cmd/envcmd/environmentcommand.go:354 +0x7e
main.init()
	/private/tmp/juju20150825-24950-1n3wstt/juju-core_1.24.5/src/github.com/juju/juju/cmd/juju/upgradejuju.go:417 +0x56

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

**Comment by gAmUssA** [comment]
+1 to @fenris 
Still doesn't work ;(

**Comment by mattyw** [comment]
@gAmUssA @fenris I'm sorry you're both having trouble are you both building from source or doing it from a release?

**Comment by fenris** [comment]
building from source ... using homerew ...

**Comment by fenris** [comment]
@mattyw any update for this issue?

**Comment by anastasiamac** [comment]
We no longer generate config in Juju 2.0.

We track our bugs in launchpad. If you are experiencing failures, feel free to file a bug in https://bugs.launchpad.net/juju/
