### ISSUE TITLE
juju bootstrap fails to work due to incorrect Identities restriction. 

### ISSUE THREAD

**Issue by NeilW** [juju/juju#2920]
Using manual environment, 1.24 no longer allows ssh-agent bootstraps from a cloud machine jump box. 

The identities code breaks using a cloud machine as a jump box - where no private key is stored on the jump box and you are relying on ssh-agent in the normal cloud fashion.

With 1.22.6 the ssh command  on 'juju bootstrap' is:

ssh -o "StrictHostKeyChecking no" -o "PasswordAuthentication no" -o "ServerAliveInterval 30" -i /home/ubuntu/.juju/ssh/juju_id_rsa ubuntu@srv-yyjtm.gb1s.brightbox.com sudo -n /bin/bash

with 1.24.3 the ssh command on 'juju bootstrap' is:

ssh -o "StrictHostKeyChecking no" -o "PasswordAuthentication no" -o "ServerAliveInterval 30" -o "IdentitiesOnly yes" -i /home/ubuntu/.juju/ssh/juju_id_rsa ubuntu@srv-p8mn4.gb1s.brightbox.com sudo -n true

This is despite the 'juju_id_rsa' file not existing at this point in the process.

**Comment by kat-co** [comment]
@NeilW hey, tyvm for the bug report! I'm working on getting this resolved for you. I've moved it over to [Launchpad](https://bugs.launchpad.net/juju-core/+bug/1486074) so we can track it against milestones, etc.

Do you have an account over there so I can ask some questions?

**Comment by NeilW** [comment]
Yup.

**Comment by kat-co** [comment]
Awesome, I'm going to close this out and hop over there. Thanks again :)
