### ISSUE TITLE
"image-metadata-url" should be used using lxc 

### ISSUE THREAD

**Issue by thomnico** [juju/juju#3153]
When deploying in a container the source of images is hard coded as https://cloud-images.ubuntu.com/query (see cloud-tools)..

One should expect that "image-metadata-url" is being used for consistency with the other ways of deploying.

Pull request #2645 provide an example of how to change this parameter (pass to cloud-tools)..

Thanks to make all ways to deploy consistent with the image source chosen.

**Comment by anastasiamac** [comment]
This has been addressed.
