### ISSUE TITLE
Juju on Windows 10 Enterprise

### ISSUE THREAD

**Issue by fenris** [juju/juju#3179]
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\KhairulAizat>juju status
panic: osVersion reported an error: unknown series "Windows 10 Enterprise"

goroutine 1 [running]:
runtime.panic(0x10331c0, 0x16640478)
        /var/lib/jenkins/curtis/golang-1.2.1/src/pkg/runtime/panic.c:266 +0xa6
github.com/juju/juju/version.mustOSVersion(0x157d078, 0x6)
        /tmp/tmpkM0WF2/juju-core_1.24.5/src/github.com/juju/juju/version/osversion.go:26 +0x9a
github.com/juju/juju/version.init()
        /tmp/tmpkM0WF2/juju-core_1.24.5/src/github.com/juju/juju/version/version.go:36 +0x38d
github.com/juju/juju/tools.init()
        /tmp/tmpkM0WF2/juju-core_1.24.5/src/github.com/juju/juju/tools/tools.go:20 +0x4d
main.init()
        /tmp/tmpkM0WF2/juju-core_1.24.5/src/github.com/juju/juju/cmd/juju/upgradejuju.go:417 +0x43

C:\Users\KhairulAizat>

Before I upgrade, I'm using Windows 8.1 Enterprise and juju working fine.

**Comment by bogdanteleaga** [comment]
What version of juju are you using?

Windows 10 support is currently only in master and 1.25

**Comment by fenris** [comment]
as stated in the error above, I'm using 1.24.5 
is there any juju 1.25 installer for windows available for download ?

**Comment by bogdanteleaga** [comment]
Yup, in the usual spot.

https://launchpad.net/juju-core/+milestone/1.25-alpha1

**Comment by fenris** [comment]
C:\Users\KhairulAizat>juju --version
1.25-alpha1-win10-i386

C:\Users\KhairulAizat>juju status --debug
2015-09-07 11:54:48 INFO juju.cmd supercommand.go:37 running juju [1.25-alpha1-win10-i386 gc]
2015-09-07 11:54:48 DEBUG juju.api api.go:162 no cached API connection settings found
2015-09-07 11:54:48 DEBUG juju.provider.azure environprovider.go:25 opening environment "azure".
2015-09-07 11:54:53 ERROR juju.cmd supercommand.go:429 Unable to connect to environment "azure".
Please check your credentials or use 'juju bootstrap' to create a new environment.

Error details:
instances not found

Thanks @bogdanteleaga  \0/
