### ISSUE TITLE
Juju service invalid name ending in number.

### ISSUE THREAD

**Issue by skylerberg** [juju/juju#3191]
When writing some tests with amulet I got an error saying that my service name was invalid. I was running a command such as:
`deployment.add("cinder-1", charm="cinder", series="trusty)`

Changing this to the following fixed the problem:
`deployment.add("cinder-one", charm="cinder", series="trusty")`

This is not a big deal, and may not even be a bug, but I am not sure why such a name would be invalid.

I put this in Juju rather than amulet because I am pretty sure that the problem is with the juju command being used by amulet, not with amulet itself.

**Comment by mattyw** [comment]
@skylerberg we don't allow service names like this as they can be easily confused with other things in the system like charm urls which have name-revisionNumber at the end. They could also be confused with unit numbers which are serviceName/unitNumber. A service called cinder-1 would look potentially confusing as cinder-1/0 cinder-1/1. 

As far as I know this is a usability decision.

Thanks for your report though.

**Comment by skylerberg** [comment]
@mattyw That makes sense. Thanks for the reply.
