### ISSUE TITLE
storageprovider seems to be stuck in an infinite loop

### ISSUE THREAD

**Issue by cholcombe973** [juju/juju#3366]
I'm running juju 1.24.6-trusty-amd64 and my logs are filling up with these messages:

machine-113[552]: 2015-09-24 15:06:16 ERROR juju.worker runner.go:223 exited "storageprovisioner-machine": processing pending volume attachments: creating volume attachments: attaching volumes from source "loop": attaching volume 113/4: attaching loop device: /var/lib/juju/storage/loop/volume-113-4: No such file or directory: exit status 1

I think the problem is that I tried to deploy a charm that had storage requirements but I never allocated them.  

I can't remove-service or destroy-machine --force to stop it.

**Comment by mattyw** [comment]
Thanks @cholcombe973, we'll take a look

**Comment by axw** [comment]
Sorry, storage is experimental in 1.24, and should have been behind a feature flag; it will be in 1.24.7. Please give 1.25 a shot when it's released (imminently, so I'm told).

**Comment by kat-co** [comment]
Hi, sorry for the long delay. We usually track issues here: https://bugs.launchpad.net/juju-core

Is this still an issue for you?

**Comment by cholcombe973** [comment]
Yeah it's still an issue.  I'm happy to track it on launchpad.  Thanks :)

**Comment by kat-co** [comment]
That would be great! I've opened the bug for you here: https://bugs.launchpad.net/juju-core/+bug/1546805
