### ISSUE TITLE
Env inconsistencies between actual hook context & debug-hooks

### ISSUE THREAD

**Issue by johnsca** [juju/juju#3449]
Reported on the list: https://lists.ubuntu.com/archives/juju/2015-October/005819.html

It seems that the home directory, among other aspects of the environment, differ between a proper hook context and debug-hooks.  My guess is that it's due to debug-hooks starting off as an ssh session logged in as the ubuntu user.  These discrepancies can lead to unexpected bugs in charms; we also ran into this at one point while working on the Big Data charms.

**Comment by kat-co** [comment]
Hi, sorry for the long delay. We usually track issues here: https://bugs.launchpad.net/juju-core

Is this still an issue for you?

**Comment by johnsca** [comment]
We haven't run in to it since then, but it might be worth following up with Merlijn on the mailing list, as it was affecting him more than us.
