### ISSUE TITLE
Clearer error message when servicename instead of unitname

### ISSUE THREAD

**Issue by galgalesh** [juju/juju#3464]
Some command like `juju debug-hooks` require the name of a unit aka `<servicename>/<unitnr>`. I think it is common for people who start with Juju to mix service and unit names. even now, I regularly type `juju debug-hooks <servicename>`.

It would be great if the error message for this command recognized that you typed something that looks like a servicename and advise you to append `/<unitnr>` to the service name to fix the problem.

**Comment by mattyw** [comment]
@galgalesh this seems like a good idea to me. I've raised an launchpad bug for it

https://bugs.launchpad.net/juju-core/+bug/1508392

Many thanks for the suggestions
