### ISSUE TITLE
Local provider stops working after reboot Ubuntu 15.04

### ISSUE THREAD

**Issue by galgalesh** [juju/juju#3483]
Hi

I'm running Ubuntu 15.04. After a reboot, the local provider stops working. `juju status` doesn't return anything. `lxc-ls --fancy` shows the correct machines started up, and `ps-auxf | grep juju` shows the daemons running.

```
root      9156  0.0  0.4 295692 35176 ?        Ssl  11:32   0:00      \_ /var/lib/juju/tools/machine-1/jujud machine --data-dir /var/lib/juju --machine-id 1 --debug
root      9194  0.0  0.4 295692 34516 ?        Ssl  11:32   0:00      \_ /var/lib/juju/tools/unit-rest2jfed-0/jujud unit --data-dir /var/lib/juju --unit-name rest2jfed/0 --debug
root      5418  0.0  0.4 238608 34628 ?        Ssl  09:42   0:03      \_ /var/lib/juju/tools/machine-2/jujud machine --data-dir /var/lib/juju --machine-id 2 --debug
root      5419  0.0  0.4 238608 34556 ?        Ssl  09:42   0:03      \_ /var/lib/juju/tools/unit-tengu-instance-admin-0/jujud unit --data-dir /var/lib/juju --unit-name tengu-instance-admin/0 --debug
```

However, I think I should see the state server is missing in this output. It seems that the state server hasn't been started. What could be the cause of this?

Kind regards
Merlijn

**Comment by mattyw** [comment]
Hi @galgalesh. In local mode your machine basically becomes the state server. It does this by just running two services:
```
juju-db-<username>-local
juju-agent-<username>-local
```

I'd suspect one of these isn't running, which is why you don't get anything from juju status. Can you try to get these services running (probably just a sudo start ...) should be enough. From there we can try to work out why they didn't come up after the reboot

**Comment by mattyw** [comment]
@galgalesh Are you still having this issue?

**Comment by galgalesh** [comment]
Hi Matt


Thank you for the reminder! I am still having this issue. I can reconnect
to the local environment after running the following commands:

    sudo service juju-db-$USER-local start
    sudo service juju-agent-$USER-local start




2015-11-18 14:13 GMT+01:00 Matt Williams <notifications@github.com>:

**Comment by kat-co** [comment]
Hi, sorry for the long delay. We usually track issues here: https://bugs.launchpad.net/juju-core

Is this still an issue for you?

I should also note that our recommended approach for local development is now the LXD provider. I think you'll find it's a much nicer experience.
