### ISSUE TITLE
ERROR failed to bootstrap environment: subprocess encountered error code 255

### ISSUE THREAD

**Issue by nitinrpatil** [juju/juju#3627]
I have installed Ubuntu Server 15.10 with MAAS on a machine and have configured two nodes with the MAAS Server. The nodes are commissioned and have their state as Ready. When I am running the command "juju bootstrap", I am getting the error "ERROR failed to bootstrap environment: subprocess encountered error code 255" after a long time (around 30 minutes or more).

The complete log of the command output is as follows:

==================================================================
root@ubuntu:/home/abhijeet# juju bootstrap
Bootstrapping environment "maas"
Starting new instance for initial state server
Launching instance
WARNING no architecture was specified, acquiring an arbitrary node
  /MAAS/api/1.0/nodes/node-19307600-7e30-11e5-8eb1-001cc0f8442d/
Installing Juju agent on bootstrap instance
Waiting for address
Attempting to connect to client2.maas:22
Attempting to connect to client2.maas:22
Attempting to connect to 192.168.1.18:22
Warning: the ECDSA host key for 'client2.maas' differs from the key for the IP address '192.168.1.18'
Offending key for IP in /root/.ssh/known_hosts:2
Matching host key in /root/.ssh/known_hosts:3
Logging to /var/log/cloud-init-output.log on remote host
Running apt-get update
Running apt-get upgrade
Installing package: curl
Installing package: cpu-checker
packet_write_wait: Connection to 192.168.1.18: Broken pipe
ERROR failed to bootstrap environment: subprocess encountered error code 255

======================================================================

Please suggest any solution. Thanks in advance!

**Comment by mattyw** [comment]
@nitinrpatil sorry you're having issues, can you try running with juju bootstrap --debug to see if that throws up anything more?

As this is a specific issues I'd recommend emailing the juju mailing list juju@lists.ubuntu.com. We should be able to find someone to resolve your issue fairly quickly

**Comment by nitinrpatil** [comment]
@mattyw thanks for the reply!

Actually, the problem has been solved. My nodes were not able to connect to the internet. So, I added my default gateway in the "Upstream DNS" option of the Settings section of MAAS Web UI. After that, the nodes were able to download packages from internet and juju bootstrapped successfully.
