### ISSUE TITLE
Storage Error

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju/juju#3791]
When adding storage that is invalid (over size limits) juju can no longer remove the machine.

For example:
```
juju switch amazon
juju bootstrap
juju deploy cs:~chris.macnaughton/trusty/ceph-osd --storage "osd-devices=ebs,2T,1"
juju destroy-service ceph-osd
```

Juju hangs on destroying the machine that the bad storage was added to.

Additionally, storage-list will return the invalid attachments, causing :
```python
storage_ids = storage_list('osd-devices')
devices.extend((storage_get('location', s) for s in storage_ids))
```
to break within a charm environment.

**Comment by wallyworld** [comment]
I've raised lp bugs to cover these issues. Progress will be tracked in lp, not here.

https://bugs.launchpad.net/juju-core/+bug/1518480
https://bugs.launchpad.net/juju-core/+bug/1518482
