### ISSUE TITLE
generate-config for azure has wrong key name

### ISSUE THREAD

**Issue by bac** [juju/juju#3975]
`juju generate-config` produces the following for azure:

```
        # application-key is the password specified when creating the application
        # in Azure Active Directory.
        application-password: XXX
```

juju actually expects `application-key` not `application-password` so the comment is correct but the slug is wrong.

**Comment by bac** [comment]
Using a hand-built juju from current master:
```
[master]bac@salchicha:~/go/src/github.com/juju/juju$ juju --version
1.26-alpha3-wily-amd64
[master]bac@salchicha:~/go/src/github.com/juju/juju$ git log
commit 8a29637e3e84385ca19537578b41d25e20faadb5
```

**Comment by marcoceppi** [comment]
handbuilt juju from master and what's in 1.25 are two different things.
There's a new azure provider in 1.26/2.0 so we'll need core to document
that for the next release of the docs, but 1.25 and the docs are correct

**Comment by marcoceppi** [comment]
That comment was meant for juju/docs#760

**Comment by bac** [comment]
Good point about the docs.  This small error is still an issue for `juju generate-config` for trunk.

**Comment by axw** [comment]
@bac Thanks, will fix the boilerplate soon. I may actually change the attribute to "-password", it's probably a bit more obvious.
