### ISSUE TITLE
bootstrap manual broken: failed to check provisioned status: subprocess encountered error code 1

### ISSUE THREAD

**Issue by ophilippsen** [juju/juju#4242]
**bootstrap manual broken**

Initial bootstrap of a new manual environment does not work.

Tested on
- Ubuntu 14.04.3.LTS

with 

- packaged Juju 1.24.7 and
- latest ppa/stable Juju 1.25.3

Testing Steps

- Install a clean, new Ubuntu 14.04.3-amd64, with new user _myuser_
- Update to latest binaries and restart
```bash
sudo aptitude update
sudo aptitude upgrade
shutdown -r now
```
- Login as _myuser_ and install packaged juju
```bash
sudo aptitude install juju
```
- Initialize Juju and create a new environment configuration
```bash
juju generate-config
```
outputs:

> A boilerplate environment configuration file has been written to /home/myuser/.juju/environments.yaml.
> Edit the file to configure your juju environment and run bootstrap.

- Modify environments.yaml in section "manual" and add hostname and username like this:
```yaml
default: amazon

environments:
    manual:
        type: manual
        # bootstrap-host holds the host name of the machine where the
        # bootstrap machine agent will be started.
        bootstrap-host: jujutest.mydomain.com

        # bootstrap-user specifies the user to authenticate as when
        # connecting to the bootstrap machine. It defaults to
        # the current user.
        bootstrap-user: myuser

    # https://juju.ubuntu.com/docs/config-aws.html
    amazon:
        type: ec2
```
- Switch to manual and try to bootstrap the environment
```bash
juju switch manual
```
outputs:

> amazon -> manual

```bash
juju bootstrap --debug
```

outputs:

> 2016-01-29 14:15:54 INFO juju.cmd supercommand.go:37 running juju [1.24.7-trusty-amd64 gc]
> 2016-01-29 14:15:54 INFO juju.provider.manual provider.go:148 enable-os-refresh-update was not defined. Defaulting to true.
> 2016-01-29 14:15:54 INFO juju.provider.manual provider.go:148 enable-os-upgrade was not defined. Defaulting to false.
> 2016-01-29 14:15:55 INFO juju.environs.manual init.go:139 initialising "jujutest.mydomain.com", user "myuser"
> 2016-01-29 14:15:55 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> 2016-01-29 14:15:55 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> myuser@jujutest.mydomain.com's password: 
> [sudo] password for myuser: 
> 2016-01-29 14:16:05 INFO juju.provider.manual provider.go:32 initialized ubuntu user
> 2016-01-29 14:16:05 DEBUG juju.provider.manual environ.go:253 using ssh storage at host "ubuntu@jujutest.mydomain.com" dir "/var/lib/juju/storage"
> 2016-01-29 14:16:05 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> 2016-01-29 14:16:05 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> 2016-01-29 14:16:05 DEBUG juju.environs.configstore disk.go:311 writing jenv file
> 2016-01-29 14:16:05 DEBUG juju.environs.configstore disk.go:435 writing jenv file to /home/myuser/.juju/environments/manual.jenv
> 2016-01-29 14:16:05 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> 2016-01-29 14:16:05 INFO juju.network network.go:214 setting prefer-ipv6 to false
> 2016-01-29 14:16:05 INFO juju.cmd cmd.go:113 Bootstrapping environment "manual"
> 2016-01-29 14:16:05 DEBUG juju.environs.bootstrap bootstrap.go:98 environment "manual" supports service/machine networks: false
> 2016-01-29 14:16:05 DEBUG juju.environs.bootstrap bootstrap.go:100 network management by juju enabled: true
> 2016-01-29 14:16:05 DEBUG juju.environs.bootstrap tools.go:73 looking for bootstrap tools: version=<nil>
> 2016-01-29 14:16:05 INFO juju.environs.tools tools.go:86 reading tools with major.minor version 1.24
> 2016-01-29 14:16:05 DEBUG juju.environs.tools urls.go:108 trying datasource "keystone catalog"
> 2016-01-29 14:16:05 DEBUG juju.environs.simplestreams simplestreams.go:659 using default candidate for content id "com.ubuntu.juju:released:tools" are {20160125 mirrors:1.0 content-download streams/v1/cpc-mirrors.sjson []}
> 2016-01-29 14:16:05 DEBUG juju.environs.simplestreams simplestreams.go:429 read metadata index at "https://streams.canonical.com/juju/tools/streams/v1/index2.sjson"
> 2016-01-29 14:16:06 DEBUG juju.environs.simplestreams simplestreams.go:968 metadata: &{map[com.ubuntu.juju:13.10:armhf:{ 1.16.2 armhf   map[20160125:0xc2101023c0]} com.ubuntu.juju:14.04:armhf:{ 1.16.2 armhf   map[20160125:0xc210102c00]} com.ubuntu.juju:14.04:ppc64:{ 1.17.2 ppc64   map[20160125:0xc2102428a0]} com.ubuntu.juju:14.10:amd64:{ 1.18.2 amd64   map[20160125:0xc210242d80]} com.ubuntu.juju:15.04:ppc64:{ 1.20.12 ppc64   map[20160125:0xc2101dc120]} com.ubuntu.juju:15.04:ppc64el:{ 1.20.12 ppc64el   map[20160125:0xc2101dc240]} com.ubuntu.juju:15.10:arm64:{ 1.22.8 arm64   map[20160125:0xc2101dc600]} com.ubuntu.juju:16.04:arm64:{ 1.25.3 arm64   map[20160125:0xc210234d20]} com.ubuntu.juju:win81:amd64:{ 1.21.1 amd64   map[20160125:0xc210240ba0]} com.ubuntu.juju:12.04:i386:{ 1.15.0 i386   map[20160125:0xc210234840]} com.ubuntu.juju:14.04:ppc64el:{ 1.17.2 ppc64el   map[20160125:0xc210242a80]} com.ubuntu.juju:15.10:amd64:{ 1.22.8 amd64   map[20160125:0xc2101dc4e0]} com.ubuntu.juju:15.10:armhf:{ 1.22.8 armhf   map[20160125:0xc2101dc780]} com.ubuntu.juju:win2012hvr2:amd64:{ 1.21.1 amd64   map[20160125:0xc2102407e0]} com.ubuntu.juju:14.04:amd64:{ 1.16.2 amd64   map[20160125:0xc2101026c0]} com.ubuntu.juju:14.10:ppc64:{ 1.18.4 ppc64   map[20160125:0xc2101236c0]} com.ubuntu.juju:16.04:armhf:{ 1.25.3 armhf   map[20160125:0xc210234e40]} com.ubuntu.juju:win2012:amd64:{ 1.21.1 amd64   map[20160125:0xc2102405a0]} com.ubuntu.juju:12.04:amd64:{ 1.15.0 amd64   map[20160125:0xc210234600]} com.ubuntu.juju:13.04:amd64:{ 1.15.0 amd64   map[20160125:0xc210234cc0]} com.ubuntu.juju:13.04:i386:{ 1.15.0 i386   map[20160125:0xc210102120]} com.ubuntu.juju:14.04:arm64:{ 1.17.2 arm64   map[20160125:0xc2101029c0]} com.ubuntu.juju:14.10:armhf:{ 1.18.2 armhf   map[20160125:0xc2101231e0]} com.ubuntu.juju:15.10:i386:{ 1.22.8 i386   map[20160125:0xc2101dc960]} com.ubuntu.juju:16.04:ppc64:{ 1.25.3 ppc64   map[20160125:0xc210240240]} com.ubuntu.juju:win2012hv:amd64:{ 1.21.1 amd64   map[20160125:0xc2102406c0]} com.ubuntu.juju:win8:amd64:{ 1.21.1 amd64   map[20160125:0xc210240cc0]} com.ubuntu.juju:14.10:i386:{ 1.18.2 i386   map[20160125:0xc210123420]} com.ubuntu.juju:15.04:i386:{ 1.20.12 i386   map[20160125:0xc210123f00]} com.ubuntu.juju:16.04:i386:{ 1.25.3 i386   map[20160125:0xc210240060]} com.ubuntu.juju:centos7:amd64:{ 1.22.8 amd64   map[20160125:0xc210240480]} com.ubuntu.juju:win2012r2:amd64:{ 1.21.1 amd64   map[20160125:0xc210240960]} com.ubuntu.juju:13.10:i386:{ 1.15.0 i386   map[20160125:0xc2101024e0]} com.ubuntu.juju:16.04:amd64:{ 1.25.3 amd64   map[20160125:0xc210234120]} com.ubuntu.juju:16.04:ppc64el:{ 1.25.3 ppc64el   map[20160125:0xc210240360]} com.ubuntu.juju:win7:amd64:{ 1.21.1 amd64   map[20160125:0xc210240a80]} com.ubuntu.juju:12.10:i386:{ 1.15.0 i386   map[20160125:0xc210234a80]} com.ubuntu.juju:13.10:amd64:{ 1.15.0 amd64   map[20160125:0xc210102240]} com.ubuntu.juju:14.04:i386:{ 1.16.2 i386   map[20160125:0xc2102420c0]} com.ubuntu.juju:14.10:arm64:{ 1.18.4 arm64   map[20160125:0xc210242f00]} com.ubuntu.juju:12.04:armhf:{ 1.16.2 armhf   map[20160125:0xc210234720]} com.ubuntu.juju:12.10:amd64:{ 1.15.0 amd64   map[20160125:0xc210234960]} com.ubuntu.juju:14.04:powerpc:{ 1.17.2 powerpc   map[20160125:0xc2102426c0]} com.ubuntu.juju:14.10:ppc64el:{ 1.18.4 ppc64el   map[20160125:0xc210123900]} com.ubuntu.juju:15.04:amd64:{ 1.20.12 amd64   map[20160125:0xc210123a20]} com.ubuntu.juju:15.04:arm64:{ 1.20.12 arm64   map[20160125:0xc210123b40]} com.ubuntu.juju:15.04:armhf:{ 1.20.12 armhf   map[20160125:0xc210123de0]} com.ubuntu.juju:15.10:ppc64:{ 1.22.8 ppc64   map[20160125:0xc2101dcde0]} com.ubuntu.juju:15.10:ppc64el:{ 1.22.8 ppc64el   map[20160125:0xc210234000]}] map[] Mon, 25 Jan 2016 20:23:35 +0000 products:1.0 com.ubuntu.juju:released:tools  }
> 2016-01-29 14:16:06 INFO juju.cmd cmd.go:113 Starting new instance for initial state server
> 2016-01-29 14:16:06 INFO juju.environs.manual init.go:35 Checking if jujutest.mydomain.com is already provisioned
> 2016-01-29 14:16:06 DEBUG juju.utils.ssh ssh.go:249 using OpenSSH ssh client
> 2016-01-29 14:16:06 ERROR juju.cmd supercommand.go:430 failed to bootstrap environment: failed to check provisioned status: subprocess encountered error code 1

**Comment by kat-co** [comment]
Pulled this into our bug tracker in Launchpad: https://bugs.launchpad.net/juju-core/+bug/1546795
