### ISSUE TITLE
lxd provider's namespace property seems to be ignored

### ISSUE THREAD

**Issue by tasdomas** [juju/juju#4388]
The comments in `juju init --show` say:
        # namespace identifies the namespace to associate with containers
        # created by the provider.  It is prepended to the container names.
        # By default the model's name is used as the namespace.

However, setting the namespace property seems to have no effect (containers have a "juju-" prefix). The environment name also does not seem to be prepended to the container names.

Running 2.0-alpha2-wily-amd64, local build, HEAD is 7b91d0fb30a03ae04c4b9c2e1da9e744a3b74ade

**Comment by kat-co** [comment]
Pulled into launchpad here: https://bugs.launchpad.net/juju-core/+bug/1546794
