### ISSUE TITLE
Destroying a model leaves stale current-model file

### ISSUE THREAD

**Issue by castrojo** [juju/juju#4410]
I had a model named "kevin". I wanted to destroy it:

    jorge@ivory:~$ juju destroy-model kevin
    WARNING! This command will destroy the "kevin" model.
    This includes all machines, services, data and other resources.

    Continue [y/N]? y

    jorge@ivory:~$ juju create-model kevin
    ERROR model "kevin" not found
    jorge@ivory:~$ juju create-model meh
    ERROR model "kevin" not found
    jorge@ivory:~$ 

Deleting `~/.local/share/juju/current-model` fixes the problem. I would think that if I delete a model and I'm currently "in" it, switch me out of it (maybe to the admin top model?).

**Comment by cherylj** [comment]
Opened https://bugs.launchpad.net/juju-core/+bug/1545589 for this issue.  Thanks!
