### ISSUE TITLE
availability zone not set

### ISSUE THREAD

**Issue by cholcombe973** [juju/juju#4452]
When deploying on the latest juju stable release of 1.25.3 on ec2 in my python hook code I'm running the following code and it's showing None as the return value:
```
    az_info = os.environ.get('JUJU_AVAILABILITY_ZONE')
    log("AZ Info: " + az_info)
```
The ec2 region that I'm deploying on is us-west-2
In my juju status output I'm seeing the following for the machine:
```
31         started 1.25.3  54.213.132.207 i-eb50d82c trusty arch=amd64 cpu-cores=1 cpu-power=300 mem=3840M root-disk=8192M availability-zone=us-west-2b
```
I looked into the Go code and it appears that it's querying and setting the environment variable.  
I also dropped into the install debug hook and tried to echo $JUJU_AVAILABILITY_ZONE and that also showed nothing.  I think this is a bug but I'm not certain.

**Comment by kat-co** [comment]
Hi, thanks for the bug report. I've opened this in our bug tracker here: https://bugs.launchpad.net/juju-core/+bug/1546790

Someone should be triaging/prioritizing this soon.
