### ISSUE TITLE
LXC Local on Beta 2?

### ISSUE THREAD

**Issue by devekko** [juju/juju#4653]
is  there still an LXC Local option on Beta 2?

the commands dont seem to exist

**Comment by mitechie** [comment]
@devekko LXC is getting replaced out with the LXD option for Xenial and Juju 2.0. There's currently a known bug around it in the beta 1 release of Juju 2.0 which should be corrected when the beta 2 drops this week.

https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1551854

**Comment by devekko** [comment]
thanks

so the docs are wrong?

https://jujucharms.com/docs/devel/config-local

points to LXC local
https://jujucharms.com/docs/devel/config-LXC

which tells you to install stable which then borks your system with two versions of juju

**Comment by mitechie** [comment]
Yes, the docs are being updated while development and the betas move forward. You should be able to run the two versions of Juju without issue side by side. You can switch which one using the update-alternatives method mentioned in the release notes here:
https://lists.ubuntu.com/archives/juju/2016-February/006618.html

**Comment by devekko** [comment]
ok, good to know, thanks indeed

have you folks ever thought about running a Nutch crawl over the various websites, lists etc and send  the results to Solr and then integrate into Drupal or some other integrated search

works well

**Comment by devekko** [comment]
btw, on the idea of running two versions of juju using  

sudo update-alternatives --config juju

off topic, idea for later

I wonder if I could use apt-get adapt without switching but instead change aliases?
