### ISSUE TITLE
error juju boostrap fail

### ISSUE THREAD

**Issue by aluguri-tarun** [juju/juju#4732]
Failed to connect to streams.canonical.com port 443: Connection tim                                                                                        ed out\ntools from https://streams.canonical.com/juju/tools/agent/1.25.3/juju-1.                                                                                        25.3-trusty-amd64.tgz downloaded: HTTP 000; time 126.336s; size 0 bytes; speed 0                                                                                        .000 bytes/s Download failed..... wait 15s\nAttempt 3 to download tools from htt                                                                                        ps://streams.canonical.com/juju/tools/agent/1.25.3/juju-1.25.3-trusty-amd64.tgz.                                                                                        ..\ncurl:

**Comment by davecheney** [comment]
Does your environment mandate a proxy server ? Can you connect to
https://streams.canonical.com/ from inside your environment ?

**Comment by aluguri-tarun** [comment]
The node i am trying to juju bootstrap had the following configuration
2NIC's
One nic which is managed by maas server(DNS &DHCP)
the other nic connected to the external network(connected to the internet)


I have attached the screen which i get on the node when i am bootstraping it.

![img_20160314_162944083](https://cloud.githubusercontent.com/assets/17767253/13810710/74ee07d8-eb71-11e5-967b-aa63cf5fcf13.jpg)

**Comment by anastasiamac** [comment]
We track our issues in launchpad: https://bugs.launchpad.net/juju-core. 
Please report it there to get further assistance.
