### ISSUE TITLE
Can't bootstrap on VSphere

### ISSUE THREAD

**Issue by ivan-exness** [juju/juju#4965]
My environments.yaml is:

```
default: vmware

environments:
    vmware:
      type: vsphere
      host: vcenter.exness.local
      user: iskiridomov
      password: w7GdbPNb
      datacenter: Cyprus
      external-network: VM Network

```

When VM is created, it has 2 network adapters (Int-Cloud-Network -that I use for maas cloud, and there maas-dhcp are working, and VM Network that is my external network with Internet access)

![screenshot 2016-04-01 18 30 35](https://cloud.githubusercontent.com/assets/17728801/14211648/e17a35a2-f837-11e5-889a-f20bcae07e17.png)

So I dont understand why juju tried to connect to Internal network insted external.

I have created IP Pools already

![screenshot 2016-04-01 18 33 56](https://cloud.githubusercontent.com/assets/17728801/14211733/50208b1e-f838-11e5-9d8b-a2d63fc7c61a.png)

```
JUJU_DEV_FEATURE_FLAGS="vsphere-provider" juju bootstrap
Bootstrapping environment "vmware"
Starting new instance for initial state server
Launching instance
WARNING Error while trying to create instance in 192.168.137.7 availability zone: failed to allocate external IP address: Warning: Identity file /var/lib/juju/system-identity not accessible: No such file or directory.
ssh: connect to host 10.10.10.107 port 22: Network is unreachable

ERROR failed to bootstrap environment: cannot start bootstrap instance: Can't create instance in any of availability zones, last error: failed to allocate external IP address: Warning: Identity file /var/lib/juju/system-identity not accessible: No such file or directory.
ssh: connect to host 10.10.10.107 port 22: Network is unreachable
```

**Comment by cherylj** [comment]
We track juju issues in launchpad.  I've opened a bug for you there:  https://bugs.launchpad.net/juju-core/+bug/1565943
