### ISSUE TITLE
Please add GPU instances from Azure

### ISSUE THREAD

**Issue by SaMnCo** [juju/juju#5162]
Hi!! 

When I bootstrap on Azure I get: 

```
juju deploy --constraints "instance-type=b1" trusty/ubuntu
Added charm "cs:trusty/ubuntu-7" to the environment.
ERROR invalid constraint value: instance-type=b1
valid values are: [ExtraSmall Small Medium Large ExtraLarge A5 A6 A7 A8 A9 Standard_D1 Standard_D2 Standard_D3 Standard_D4 Standard_D11 Standard_D12 Standard_D13 Standard_D14 Standard_G1 Standard_G2 Standard_G3 Standard_G4 Standard_G5]

```
In this list I can't find the GPU instances (N-series) which are pretty awesome on Azure. Is it possible to update the list of available instances?

Thanks,

**Comment by axw** [comment]
@SaMnCo Please file a bug at https://bugs.launchpad.net/juju-core/+filebug so it can be triaged.

Please include the Azure location you're using, and version of Juju. The new Azure provider in Juju 2.0 queries the instance types from the Azure API, so there shouldn't be a problem there, assuming you can actually access the N-series instance types. It appears that N-series is still in private preview; I don't have access to them, so can't verify.

BTW, you used "b1" in your example, but AFAIK that's not a thing. Maybe that was a typo, though.
