### ISSUE TITLE
juju 2.0 fails to resolved -r on Power + LXD

### ISSUE THREAD

**Issue by SaMnCo** [juju/juju#5177]
Hi, 
Running Juju 2.0-beta3-xenial-ppc64el  and deploying local model using LXD. 

If any of my unit gets into an error stage, and I do: 

* fix in the charm
* juju upgrade-charm <name> --force-units

==> At this point, I get into an infinite loop of extremely fast logs: 

```
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:39 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
unit-mesos-master-0: 2016-04-15 06:54:40 INFO juju.worker.uniter.storage resolver.go:65 initial storage attachments ready
unit-mesos-master-0: 2016-04-15 06:54:40 INFO juju.worker.uniter resolver.go:106 awaiting error resolution for "install" hook
```

I couldn't find how to get out of it

* juju resolved -r unit
* juju resolved unit

None fixes the problem. Furthermore, at this stage, the only way I can get out of the look (found so far) is to kill (not destroy, kill) the model, and restart all over again. 

I can reproduce at will. You just have to create an error in the deployment of a model. I don't have a xenial at hand other than this, so can't test on x86 yet. 

Thanks,

**Comment by SaMnCo** [comment]
This actually does the same without the -r. 

So any ```juju resolved <-r>``` now doesn't work, and generates tons and tons of bad logs. Any idea? This is really annoying as I always need to tear down my whole thing as soon as a charm fails. Tough when developing. 

Thanks,

**Comment by cherylj** [comment]
There's a bug in lp for this issue:  https://bugs.launchpad.net/juju-core/+bug/1566130
