### ISSUE TITLE
juju upgrade-charm should be a little more clever about what it does

### ISSUE THREAD

**Issue by SaMnCo** [juju/juju#5178]
If you 

```
juju upgrade-charm 
```

juju will bump the revision number even if you use the exact same source. This is pretty confusing. I guess if the fingerprint of the current code deployed is the same, this command should tell the user "you're trying to upgrade with an identical version" and eventually refuse to do it and would not bump the revision number. 
Thoughts?

**Comment by anastasiamac** [comment]
Thank you :D

We track our bugs and feature requests in launchpad: https://bugs.launchpad.net/juju-core

I've added https://bugs.launchpad.net/juju-core/+bug/1612112 

Feel free to close this issue here.

**Comment by mitechie** [comment]
@SaMnCo can I ask how it confused or got in the way. I'm nervous about changing this as doing a "noop" upgrade can be handy when testing things out. I'm curious what negative effect it had so we can balance out the use cases. 

I guess in the end we could warn the user and allow them to still force the upgrade even if the fingerprint is the same and try to keep a bit of best of both worlds.
