### ISSUE TITLE
Add Dreamhost to clouds list

### ISSUE THREAD

**Issue by BryanQuigley** [juju/juju#5204]
I'd like to see dreamhost added to the clouds list "juju list-clouds".   I just uses the OpenStack API, so that should be easy?

Somewhat related, why isn't openstack on that list?

**Comment by cherylj** [comment]
juju list-clouds will output public clouds that juju knows about, plus any custom clouds that users have defined using the openstack or MAAS cloud type.  A cloud type like openstack or MAAS isn't really a cloud to juju unless you've given it endpoints to talk to.
