### ISSUE TITLE
maas-server not recognized

### ISSUE THREAD

**Issue by Kriechi** [juju/juju#5212]
Hi,

I'm running MAAS 1.9 and juju beta4.
If I try to bootstrap with this command:
```
juju bootstrap --config default-series=xenial --config maas-server=192.168.101.1 foobar maas --show-log --debug
```
It fails with: `MAAS server not specified`.

However, if I use this, it works:
```
juju bootstrap --config default-series=xenial foobar maas/192.168.101.1 --show-log --debug
```

Is this a bug - or am I missing a different config setting here?

**Comment by cherylj** [comment]
The "MAAS server" is something you would add into the cloud definition through add-cloud.  The name in the cloud definition is actually "endpoint", so it's not entirely clear:

$ cat maas.yaml
clouds:
  maas:
    type: maas
    endpoint: http://192.168.100.200/MAAS/

$ juju add-cloud maas maas.yaml

Once you do that, you can bootstrap with just `juju bootstrap foobar maas`.

**Comment by cherylj** [comment]
Boo, the formatting of the example yaml was not preserved:  http://paste.ubuntu.com/16242789/
