### ISSUE TITLE
Setting maas2 feature flag

### ISSUE THREAD

**Issue by garyx** [juju/juju#5246]
Hi,

Where do I define juju 2.0 Beta5 to use the maas2 feature flag. I'm testing this on a Xenial maas setup and that uses maas 2.0 and I cannot see where that is set. It's also just experimental for now this support?

**Comment by dimitern** [comment]
@garyx Run `export JUJU_DEV_FEATURE_FLAGS=maas2` before running `juju bootstrap ...`

**Comment by garyx** [comment]
Thanks so much,

**Comment by hoenirvili** [comment]
@dimitern this must be added to dev documentation or something..

**Comment by dimitern** [comment]
@hoenirvili Indeed! It should be mentioned in the release notes though for the latest 2.0 beta5.
