### ISSUE TITLE
Can't seem to remove units or services after failure

### ISSUE THREAD

**Issue by warsaw** [juju/juju#5293]
With juju 2.0 beta6, I've been experimenting with a local charm, but the charm has problems:

```
% juju status
[Services]    
NAME          STATUS EXPOSED CHARM                        
mailman3-core error  false   local:xenial/mailman3-core-0 

[Units]         
ID              WORKLOAD-STATUS JUJU-STATUS VERSION   MACHINE PORTS PUBLIC-ADDRESS MESSAGE                         
mailman3-core/0 error           idle        2.0-beta6 0             10.74.30.198   hook failed: "storage-attached" 

[Machines] 
ID         STATE   DNS          INS-ID                                              SERIES AZ 
0          started 10.74.30.198 juju-8d79af51-015a-4283-8d87-8ab0bf1f68a3-machine-0 xenial    

|master+=|@subdivisions[~/projects/juju/charms/mailman3:1205]% juju status
[Services]    
NAME          STATUS EXPOSED CHARM                        
mailman3-core error  false   local:xenial/mailman3-core-0 

[Units]         
ID              WORKLOAD-STATUS JUJU-STATUS VERSION   MACHINE PORTS PUBLIC-ADDRESS MESSAGE                         
mailman3-core/0 error           idle        2.0-beta6 0             10.74.30.198   hook failed: "storage-attached" 

[Machines] 
ID         STATE   DNS          INS-ID                                              SERIES AZ 
0          started 10.74.30.198 juju-8d79af51-015a-4283-8d87-8ab0bf1f68a3-machine-0 xenial    
```

Fair enough!  Let's start over:

```
% juju remove-service mailman3-core
```

After a long wait, I check the status and get exactly the same output.  Based on the help for remove-service, I would have expected all services, units, and machines to be destroyed.

I also tried `juju remove-unit mailman3-core/0` and again, nothing changed.

**Comment by warsaw** [comment]
So I can kind of recover from this by doing a `juju remove-machine X --force` where X is the machine ID.  Note that `--force` is required, otherwise nothing happens. However, the service still hangs around according to `juju status`.  To clean that up, you have to `juju remove-service mailman3-core` and ignore the error that's printed:

```
% juju remove-service mailman3-core
ERROR service "mailman3-core" not found (not found)
```

After that, `juju status` shows there are no services, units, or machines.

**Comment by warsaw** [comment]
Now I'm in an even worse state.  My install hook had a bug and my unit is in an error condition:

```
% juju status
[Services]    
NAME          STATUS EXPOSED CHARM                         
mailman3-core error  false   local:xenial/mailman3-core-10 

[Units]         
ID              WORKLOAD-STATUS JUJU-STATUS VERSION   MACHINE PORTS PUBLIC-ADDRESS MESSAGE                
mailman3-core/8 error           idle        2.0-beta6 8             10.74.30.177   hook failed: "install" 

[Machines] 
ID         STATE   DNS          INS-ID                                              SERIES AZ 
8          started 10.74.30.177 juju-8d79af51-015a-4283-8d87-8ab0bf1f68a3-machine-8 xenial    

```

There seems to be nothing I can do to get rid of it.  Even the `remove-machine --force` trick above does not work.

**Comment by cherylj** [comment]
Can you try 'juju resolved mailman3-core/8'?

**Comment by warsaw** [comment]
That just returns immediately with no output.

**Comment by howbazaar** [comment]
Hi Barry,

resolved is one of those weird commands.

What it does is tells Juju that you have resolved the issue, which
removes an error flag.

You can get juju to retry the hook with:

juju resolved --retry

This should rerun the failed hook.

One thing to remember is that resolved just resolves the one issue. It
ends up being the case often that multiple hooks have errors. You go
resolved, and then the next hook has an error. You need to resolve that
one too, and so on until you are through all the hooks.

Does that make more sense?

Tim

**Comment by warsaw** [comment]
Thanks @howbazaar that does make a lot of sense.
