### ISSUE TITLE
Build instructions in README.md did not work

### ISSUE THREAD

**Issue by a31415** [juju/juju#5299]
Here are the steps taken based on the README.md at 50583f0. It appears **make install-dependencies** fails to install and run godeps. 

System:
**$ cat /etc/*rel***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

**Kernel:**
4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Go:**
Install go via go1.6.2.linux-amd64.tar.gz
export GOPATH=/home/u1/proj/goDev
export PATH=$GOPATH/bin:$PATH

**Juju via:**
go get -d -v github.com/juju/juju/...

cd $GOPATH/src/github.com/juju/juju

**Problems start occurring here:**

**[18:48:29] $ make install-dependencies **
Installing dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bzip2 is already the newest version (1.0.6-8).
bzr is already the newest version (2.7.0-2ubuntu1).
bzr set to manually installed.
ca-certificates is already the newest version (20160104ubuntu1).
zip is already the newest version (3.0-11).
zip set to manually installed.
juju-mongodb is already the newest version (2.4.10-0ubuntu6).
mercurial is already the newest version (3.7.3-1ubuntu1).
The following additional packages will be installed:
  golang-1.6 golang-1.6-doc golang-doc juju-1.25 lxc
The following NEW packages will be installed:
  git-core golang golang-1.6 golang-1.6-doc golang-doc juju-1.25 juju-local lxc
The following packages will be upgraded:
  distro-info-data
1 upgraded, 8 newly installed, 0 to remove and 23 not upgraded.
Need to get 38.9 MB of archives.
After this operation, 264 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 distro-info-data all 0.28ubuntu0.1 [3,946 B]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 git-core all 1:2.7.4-0ubuntu1 [1,464 B]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 golang-1.6-doc all 1.6.1-0ubuntu1 [2,369 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 golang-1.6 all 1.6.1-0ubuntu1 [16.8 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 golang-doc all 2:1.6-1ubuntu4 [2,808 B]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 golang all 2:1.6-1ubuntu4 [2,766 B]
Get:7 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 lxc all 2.0.0-0ubuntu2 [3,082 B]
Get:8 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 juju-1.25 amd64 1.25.5-0ubuntu3 [36.5 MB]
Get:9 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 juju-local all 1.25.5-0ubuntu3 [8,362 B]
Fetched 38.9 MB in 5s (7,734 kB/s)    
(Reading database ... 504842 files and directories currently installed.)
Preparing to unpack .../distro-info-data_0.28ubuntu0.1_all.deb ...
Unpacking distro-info-data (0.28ubuntu0.1) over (0.28) ...
Selecting previously unselected package git-core.
Preparing to unpack .../git-core_1%3a2.7.4-0ubuntu1_all.deb ...
Unpacking git-core (1:2.7.4-0ubuntu1) ...
Selecting previously unselected package golang-1.6-doc.
Preparing to unpack .../golang-1.6-doc_1.6.1-0ubuntu1_all.deb ...
Unpacking golang-1.6-doc (1.6.1-0ubuntu1) ...
Selecting previously unselected package golang-1.6.
Preparing to unpack .../golang-1.6_1.6.1-0ubuntu1_all.deb ...
Unpacking golang-1.6 (1.6.1-0ubuntu1) ...
Selecting previously unselected package golang-doc.
Preparing to unpack .../golang-doc_2%3a1.6-1ubuntu4_all.deb ...
Unpacking golang-doc (2:1.6-1ubuntu4) ...
Selecting previously unselected package golang.
Preparing to unpack .../golang_2%3a1.6-1ubuntu4_all.deb ...
Unpacking golang (2:1.6-1ubuntu4) ...
Selecting previously unselected package lxc.
Preparing to unpack .../lxc_2.0.0-0ubuntu2_all.deb ...
Unpacking lxc (2.0.0-0ubuntu2) ...
Selecting previously unselected package juju-1.25.
Preparing to unpack .../juju-1.25_1.25.5-0ubuntu3_amd64.deb ...
Unpacking juju-1.25 (1.25.5-0ubuntu3) ...
Selecting previously unselected package juju-local.
Preparing to unpack .../juju-local_1.25.5-0ubuntu3_all.deb ...
Unpacking juju-local (1.25.5-0ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up distro-info-data (0.28ubuntu0.1) ...
Setting up git-core (1:2.7.4-0ubuntu1) ...
Setting up golang-1.6-doc (1.6.1-0ubuntu1) ...
Setting up golang-1.6 (1.6.1-0ubuntu1) ...
Setting up golang-doc (2:1.6-1ubuntu4) ...
Setting up golang (2:1.6-1ubuntu4) ...
Setting up lxc (2.0.0-0ubuntu2) ...
Setting up juju-1.25 (1.25.5-0ubuntu3) ...
Setting up juju-local (1.25.5-0ubuntu3) ...

**Following command fails**

**[18:49:53] $ go install -v github.com/juju/juju/...**
provider/azure/environ.go:13:2: cannot find package "github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest" in any of:
	/usr/local/go/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest (from $GOROOT)
	/home/u1/proj/goDev/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest (from $GOPATH)
provider/azure/config.go:10:2: cannot find package "github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/azure" in any of:
	/usr/local/go/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/azure (from $GOROOT)
	/home/u1/proj/goDev/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/azure (from $GOPATH)
provider/azure/environ.go:14:2: cannot find package "github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/to" in any of:
	/usr/local/go/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/to (from $GOROOT)
	/home/u1/proj/goDev/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/to (from $GOPATH)
provider/azure/environ.go:17:2: no buildable Go source files in /home/u1/proj/goDev/src/github.com/Azure/azure-sdk-for-go/arm/resources
provider/azure/internal/azuretesting/senders.go:13:2: cannot find package "github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/mocks" in any of:
	/usr/local/go/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/mocks (from $GOROOT)
	/home/u1/proj/goDev/src/github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest/mocks (from $GOPATH)

**davechenney from #juju-dev IRC suggested:**

**[18:50:59] 1 $ godeps -u dependencies.tsv**
godeps: command not found

**davechenney from #juju-dev IRC then suggested:
**
**[18:57:59] 127 $ go get launchpad.net/godeps**

**[18:59:20] $ godeps -u dependencies.tsv**
github.com/juju/httprequest now at 89d547093c45e293599088cc63e805c6f1205dc0
github.com/Azure/azure-sdk-for-go now at 9f40dc1ee704920d20418200ddf6ec382456bb0e
golang.org/x/oauth2 now at 11c60b6f71a6ad48ed6f93c65fa4c6f9b1b5b46a
gopkg.in/juju/charmstore.v5-unstable now at 745fa1ca2260cdc9dd5a6df6282da51776baa59f
github.com/juju/retry now at 62c62032529169c7ec02fa48f93349604c345e1f
github.com/juju/xml now at eb759a627588d35166bc505fceb51b88500e291e
launchpad.net/gnuflag now at roger.peppe@canonical.com-20140716064605-pk32dnmfust02yab
github.com/juju/govmomi now at 4354a88d4b34abe467215f77c2fc1cb9f78b66f7
github.com/juju/errors now at 1b5e39b83d1835fa480e0c2ddefb040ee82d58b3
golang.org/x/crypto now at aedad9a179ec1ea11b7064c57cbc6dc30d7724ec
github.com/juju/ratelimit now at aa5bb718d4d435629821789cb90970319f57bfe5
gopkg.in/amz.v3 now at 345e9291dbc9e6dd7b6c6c679b32b6d3366ca851
gopkg.in/macaroon-bakery.v1 now at fddb3dcd74806133259879d033fdfe92f9e67a8a
github.com/coreos/go-systemd now at 2d21675230a81a503f4363f4aa3490af06d52bb8
github.com/mattn/go-runewidth now at d96d1bd051f2bd9e7e43d602782b37b93b1b5666
gopkg.in/juju/charmrepo.v2-unstable now at c457416da598dffa665fc75aeb5c7265ff1273c0
github.com/dustin/go-humanize now at 145fabdb1ab757076a70a886d092a3af27f66f4c
github.com/juju/usso now at 68a59c96c178fbbad65926e7f93db50a2cd14f33
github.com/gorilla/websocket now at 13e4d0621caa4d77fd9aa470ef6d7ab63d1a5e41
gopkg.in/juju/jujusvg.v1 now at a60359df348ef2ca40ec3bcd58a01de54f05658e
github.com/ajstarks/svgo now at 89e3ac64b5b3e403a5e7c35ea4f98d45db7b4518
github.com/joyent/gocommon now at 40c7818502f7c1ebbb13dab185a26e77b746ff40
github.com/juju/cmd now at ca63dd8ba13f8fbbbe16a917696a7ce68cc3dc0b
github.com/juju/romulus now at df735617fa6a358e42bb71ff74b3c3ba4faf9f5f
gopkg.in/mgo.v2 now at 4d04138ffef2791c479c0c8bbffc30b34081b8d9
github.com/lxc/lxd now at 62f62e9d6e0da14947023f99764eac29c26cef8d
golang.org/x/net now at ea47fc708ee3e20177f3ca3716217c4ab75942cb
google.golang.org/api now at 0d3983fb069cb6651353fc44c5cb604e263f2a93
update github.com/gabriel-samfira/sys failed; trying to fetch newer version
github.com/gabriel-samfira/sys now at 9ddc60d56b511544223adecea68da1e4f2153beb
gopkg.in/ini.v1 now at 776aa739ce9373377cd16f526cdf06cb4c89b40f
github.com/godbus/dbus now at 88765d85c0fdadcd98a54e30694fa4e4f5b51133
github.com/bmizerany/pat now at 48be7df2c27e1cec821a3284a683ce6ef90d9052
github.com/joyent/gosdc now at 2f11feadd2d9891e92296a1077c3e2e56939547d
github.com/julienschmidt/httprouter now at 77a895ad01ebc98a4dc95d8355bc825ce80a56f6
gopkg.in/natefinch/npipe.v2 now at e562d4ae5c2f838f9e7e406f7d9890d5b02467a9
github.com/juju/idmclient now at 1995850da11150fb9247e43c6089e54eaeaae44a
github.com/joyent/gosign now at 0da0d5f1342065321c97812b1f4ac0c2b0bab56c
github.com/juju/names now at 8a0aa0963bbacdc790914892e9ff942e94d6f795
github.com/juju/utils now at 951b27b4808bad43b9107412e002576c9d1b18bb
google.golang.org/cloud now at f20d6dcccb44ed49de45ae3703312cb46e627db1
gopkg.in/juju/charm.v6-unstable now at 2abaaba0b99627e16a4f1bf8221f7330924f962f

**[19:00:12] $ go install -v github.com/juju/juju/...**
(Successfully Builds).

**[19:03:58] $ ../../../../bin/juju version**
2.0-beta7-xenial-amd64

**Comment by anastasiamac** [comment]
Thank you for finding and reporting this bug :D

We track our bugs in launchpad: https://bugs.launchpad.net/juju-core

I've added https://bugs.launchpad.net/juju-core/+bug/1612110

Feel free to close this issue here.
