### ISSUE TITLE
Cannot deploy juju-gui on the openstack internal juju environment. 

### ISSUE THREAD

**Issue by shadaab** [juju/juju#5340]
HI.
I am running juju version 1.25.5-trusty-amd64.
I get this error while deploying juju-gui in the internal juju environment of the openstack cloud.

landscape@juju-machine-0-lxc-1:~$ juju deploy --to 0 juju-gui
ERROR cannot load cookies: file locked for too long; giving up: cannot acquire lock: open /home/ubuntu/.go-cookies.lock: permission denied

These are the steps that i followed:
1.export JUJU_HOME=~/.cloud-install/juju
2. juju ssh landscape-server/0 sudo 'JUJU_HOME=/var/lib/landscape/juju-homes/sudo ls -rt /var/lib/landscape/juju-homes/ | tail -1 sudo -u landscape -E bash'
3.juju status
4juju deploy --to 0 juju-gui

Is this the correct way of deploying juju-gui in the internal juju environment?

**Comment by cherylj** [comment]
It looks like since you used 'sudo' for some of the commands, that you cannot take the lock as it was created by root.  If you do 'sudo juju deploy --to 0 juju-gui', it should probably work.

Was there a reason you needed sudo for some of the commands?

**Comment by shadaab** [comment]
No, I​ haven't used sudo with any commands during installation.

I tried to do 'sudo juju deploy --to 0 juju-gui' but I dont know the password for the landscape user.

I have installed the cloud using the OpenStack-autopilot.

**Comment by cherylj** [comment]
May be related to https://bugs.launchpad.net/bugs/1534643

**Comment by anastasiamac** [comment]
We track out bug on https://bugs.launchpad.net/juju-core
Please add a bur report there if you are still experiencing this issue.
