### ISSUE TITLE
juju bootstrap with 2.0 for first time links to non-existent docs

### ISSUE THREAD

**Issue by lutostag** [juju/juju#5357]
ubuntu@xenialmojo:~$ juju bootstrap
    Welcome to Juju 2.0-beta6. If you meant to use Juju 1.25.5 you can continue using it
    with the command juju-1 e.g. 'juju-1 switch'.
    See https://jujucharms.com/docs/stable/introducing-2 for more details.
    error: controller name and cloud name are required
ubuntu@xenialmojo:~$

https://jujucharms.com/docs/stable/introducing-2 is a 404 for me.

**Comment by cherylj** [comment]
I am able to reach that page today.  Can you check that you can as well?

**Comment by lutostag** [comment]
Yep, now I get forwarded to a placeholder page which links to where I need to go and is fine for me. Thanks!
