### ISSUE TITLE
Juju bridges get stomped 

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju#5409]
Initially, a juju deployed maas node gets bridges created on its interfaces, but following a reboot of the node, /etc/network/interfaces gets stomped, and juju created bridges are wiped.

**Comment by frobware** [comment]
Is this MAAS 1.9 or MAAS 2.0?

**Comment by jamesbeedy** [comment]
2.0

**Comment by dimitern** [comment]
@jamesbeedy Can we close this now, considering you had a lot better success with recent 2.0 betas?

**Comment by jamesbeedy** [comment]
Entirely! Thanks guys!
