### ISSUE TITLE
ERROR invalid config: no addresses match

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju#5411]
Bootstrapping the lxd provider with network bridged to a bridge on an external network interface gives -> 'ERROR invalid config: no addresses match'.

juju version -> 2.0-beta7~20160512~3966~0bd48e6f-20160512+3966+0bd48e6f~16.04

juju bootstrap lxd-test lxd --upload-tools --debug -> http://paste.ubuntu.com/16471213/

**Comment by perrito666** [comment]
This is being addressed in https://bugs.launchpad.net/juju-core/+bug/1571593
