### ISSUE TITLE
juju bootstrap error

### ISSUE THREAD

**Issue by sufyan68** [juju/juju#5531]
Hi,
If i got this error after running `juju bootstrap`

> juju.provider.manual provider.go:29 initializing ubuntu user: subprocess encountered error code 255 (Permission denied (publickey).)

what does it mean?

thank you

**Comment by anastasiamac** [comment]
We track our bugs in https://bugs.launchpad.net/juju-core
Please log a bug there, stating what version of juju you are running as well as the full output you got.
Thank you for the bug.
