### ISSUE TITLE
Ghost models exist after being destroyed

### ISSUE THREAD

**Issue by wurde** [juju/juju#5550]
Models appear to persist after being destroyed. 

JuJu: 2.0-beta8-xenial-amd64
Series: Xenial
Localhost on LXD

```Bash
wurde@solace:~/GitLab/charm-netdata$ juju list-models
MODEL     OWNER        STATUS      LAST CONNECTION
admin     admin@local  available   3 hours ago
devenv    admin@local  destroying  3 hours ago
default*  admin@local  available   18 minutes ago
devenv1   admin@local  destroying  18 minutes ago
```

I even went in and removed the containers using the `lxc delete` command manually and same result.

**Comment by anastasiamac** [comment]
Open bug in lp: https://bugs.launchpad.net/juju-core/+bug/1589774

**Comment by wurde** [comment]
@anastasiamac ty
