### ISSUE TITLE
There is no way to change networkDefaultName for GCE provider?

### ISSUE THREAD

**Issue by kerncore** [juju/juju#5762]
Hi, 

Unfortunately I can't find flexible way to change the
networkDefaultName = "default" when GCE provider is used or use multiple network's with GCE.

May you have some roadmap related to that or feature request?

**Comment by cherylj** [comment]
Yeah, I don't see a place where the network name can be set.  I do not know of any plans to change this in future releases, but you can open up a bug in Launchpad to request this ability.  (We track bugs / requests in launchpad, rather than github)
