### ISSUE TITLE
Google cloud credentials hang after X days.

### ISSUE THREAD

**Issue by ghost** [juju/juju#5796]
Twice I've bootstrapped a Google cloud and had the original credentials age out? I don't really know, but after X number of days the juju cli can no longer connect to the platform. Any commands such as `juju list-models` just hang.

**Comment by cherylj** [comment]
What's the output of juju list-models --debug?

**Comment by wurde** [comment]
I've since re-issued credentials. I'll try to recreate the issue and post the output though it seemed to be after an arbitrary number of days of inactivity.

**Comment by anastasiamac** [comment]
If you recreate the issue, please file a bug on launchpad at https://bugs.launchpad.net/juju-core, providing reproducible scenario and logs
