### ISSUE TITLE
Adding machine with interface name too long breaks bridge

### ISSUE THREAD

**Issue by scipioni** [juju/juju#6241]
Consider  a host with 10g interface named **enp5s0f0** and a deploy that has vlan on this interface, id=1409 for example.
After "juju add-machine" operation on new node is created a new bridge named br-enp5s0f0.140, not br-enp5s0f0.1409.

The maximum length of the interface name created by 'brctl addbr' is 15.

**Comment by anastasiamac** [comment]
Thank you for bringing it up for our attention \o/

We track our issues and bugs on launchpad: https://bugs.launchpad.net/juju

I've filed a bug to track this - https://bugs.launchpad.net/juju/+bug/1623373
