### ISSUE TITLE
Unable to deploy local directory on juju2 beta 17 or 18

### ISSUE THREAD

**Issue by cholcombe973** [juju/juju#6256]
I'm not entirely sure why but juju beta 17 and 18 refuses to deploy my gluster charm from the local directory.  I have some debug messages here:
```
~/repos/gluster-charm$ juju deploy . --series xenial -n 2 --debug
08:23:17 INFO  juju.cmd supercommand.go:63 running juju [2.0-beta17 gc go1.6]
08:23:17 INFO  juju.juju api.go:74 connecting to API addresses: [54.186.50.179:17070 172.31.44.242:17070]
08:23:17 INFO  juju.api apiclient.go:505 dialing "wss://54.186.50.179:17070/model/52406221-0326-40d3-87f0-b7a3a7b526a7/api"
08:23:17 INFO  juju.api apiclient.go:505 dialing "wss://172.31.44.242:17070/model/52406221-0326-40d3-87f0-b7a3a7b526a7/api"
08:23:17 INFO  juju.api apiclient.go:300 connection established to "wss://54.186.50.179:17070/model/52406221-0326-40d3-87f0-b7a3a7b526a7/api"
08:23:17 DEBUG juju.juju api.go:248 API hostnames unchanged - not resolving
08:23:17 DEBUG juju.cmd.juju.application deploy.go:695 cannot interpret as local bundle: read .: is a directory
08:23:17 DEBUG httpbakery client.go:244 client do POST https://54.186.50.179:17070/model/52406221-0326-40d3-87f0-b7a3a7b526a7/charms?revision=3&schema=local&series=xenial {
08:23:21 DEBUG httpbakery client.go:246 } -> error <nil>
08:23:21 INFO  cmd cmd.go:129 Deploying charm "local:xenial/gluster-4".
08:23:21 DEBUG juju.api apiclient.go:556 health ping failed: connection is shut down
08:23:21 ERROR cmd supercommand.go:458 charm "local:xenial/gluster-4" not found (not found)
08:23:21 DEBUG cmd supercommand.go:459 (error details: [{github.com/juju/juju/cmd/juju/application/deploy.go:779: } {github.com/juju/juju/api/charms/client.go:54: } {github.com/juju/juju/api/apiclient.go:616: } {github.com/juju/retry/retry.go:187: } {github.com/juju/juju/rpc/client.go:149: } {charm "local:xenial/gluster-4" not found (not found)}])```

The directory contents to me looks like any other charm.  Juju 1.25.x deployed it just fine. 
```
tree
.
├── actions
│   ├── create-volume-quota -> ../hooks/main
│   ├── delete-volume-quota -> ../hooks/main
│   ├── list-volume-quotas -> ../hooks/main
│   └── set-volume-options -> ../hooks/main
├── actions.yaml
├── Cargo.lock
├── Cargo.toml
├── config.yaml
├── COPYRIGHT
├── hooks
│   ├── brick-storage-attached -> main
│   ├── brick-storage-detaching -> main
│   ├── config-changed -> main
│   ├── fuse-relation-changed -> main
│   ├── fuse-relation-joined -> main
│   ├── helpers.sh
│   ├── install
│   ├── main
│   ├── nfs-relation-changed -> main
│   ├── nfs-relation-joined -> main
│   ├── server-relation-changed -> main
│   ├── start
│   └── stop
├── icon.svg
├── metadata.yaml
├── README.md
├── revision
└── src
    ├── actions.rs
    ├── block.rs
    └── main.rs

3 directories, 29 files
```
```
juju --version
2.0-beta17-trusty-amd64
```
charm proof passes just fine.  Anything else that is helpful to debug this I'm happy to provide :)

**Comment by anastasiamac** [comment]
We track out bugs on launchpad: https://bugs.launchpad.net/juju

I have filed this bug to cater for this failure: https://bugs.launchpad.net/juju/+bug/1624159
