### ISSUE TITLE
juju lxd provider displays IPv6 addresses by default

### ISSUE THREAD

**Issue by diezd** [juju/juju#6299]
I just updated to juju 2.0-rc1 and when I deploy locally to lxd provider, I get IPv6 addresses in the DNS section as follows. Not useful if I want to plug in IPv4 addresses into browser to get to service.

MODEL      CONTROLLER  CLOUD/REGION         VERSION
mediawiki  lxd-test    localhost/localhost  2.0-rc1

APP        VERSION  STATUS   SCALE  CHARM      STORE       REV  OS      NOTES
mediawiki           error        1  mediawiki  jujucharms    3  ubuntu
mysql               unknown      1  mysql      jujucharms   29  ubuntu

UNIT         WORKLOAD  AGENT  MACHINE  PUBLIC-ADDRESS                          PORTS  MESSAGE
mediawiki/0  error     idle   0        fd7d:5302:b579:fe10:216:3eff:fe14:70ef         hook failed: "db-relation-changed" for mysql:db
mysql/0      unknown   idle   1        fd7d:5302:b579:fe10:216:3eff:fed3:68cb

MACHINE  STATE    DNS                                     INS-ID         SERIES  AZ
0        started  fd7d:5302:b579:fe10:216:3eff:fe14:70ef  juju-a829a2-0  trusty
1        started  fd7d:5302:b579:fe10:216:3eff:fed3:68cb  juju-a829a2-1  trusty

RELATION  PROVIDES   CONSUMES  TYPE
db        mediawiki  mysql     regular
cluster   mysql      mysql     peer

**Comment by anastasiamac** [comment]
Thank you for filing the bug! 
We track out issues in launchpad: https://bugs.launchpad.net/juju.
Looks like you have already reported a bug there for this: https://bugs.launchpad.net/bugs/1626097
I'll close this issue.
