### ISSUE TITLE
New cloud provider

### ISSUE THREAD

**Issue by jasminSPC** [juju/juju#6653]
Hey guys,

I'm about to start working on adding a new cloud provider for juju. I was wondering if there are any guidelines on how to do that. I found this https://github.com/juju/juju/blob/master/CONTRIBUTING.md but is there anything else?

Thanks

**Comment by anastasiamac** [comment]
@jasminSPC,
Thank you for a great question!
There should be more information on our wiki https://github.com/juju/juju/wiki, specifically you might find https://github.com/juju/juju/wiki/Implementing-environment-providers helpful \o/
