### ISSUE TITLE
Juju behind proxy

### ISSUE THREAD

**Issue by natejgardner** [juju/juju#6664]
When using a corporate proxy, Juju bootstrap is unable to contact cloud-images.ubuntu.com. It appears that Juju simply doesn't have proxy support.

**Comment by bz2** [comment]
If you're using proxies, you need to configure them. See:

https://jujucharms.com/docs/2.0/models-config

**Comment by natejgardner** [comment]
I configured the proxies according to this documentation, but it's still broken.

**Comment by anastasiamac** [comment]
Let's track this in launchpad https://bugs.launchpad.net/juju-core/+bug/1647897
I've added the above details...
