### ISSUE TITLE
Error: no image metadata found

### ISSUE THREAD

**Issue by nurfet-becirevic** [juju/juju#6756]
Hey guys,

I am implementing a new cloud provider for Juju. When I try bootstrapping in the interactive mode I keep receiving "ERROR failed to bootstrap model: no image metadata found". What methods should I implement  to provide the metadata? Could someone shed some light on the bootstrap magic?

I've been referring to https://github.com/juju/juju/wiki/Implementing-environment-providers but I couldn't find enough information to solve the problem. Also, it appears that some infos in the document are obsolete?

**Comment by perrito666** [comment]
Hey hey, sorry no one answered this before, bug tracking for this project is done at https://bugs.launchpad.net/juju/ in this case if you want to have a more direct conversation with us you can always go to irc channel #juju-dev at freenode or join our list juju@lists.ubuntu.com 
If you are going for the bug aproach please provide some information about your provider and perhaps a few logs.
Cheers.
