### ISSUE TITLE
Called "Application" in most places, but called "App" in 'juju status'

### ISSUE THREAD

**Issue by Meai1** [juju/juju#6824]
I think it should be called the same if it's the same, this stuff is confusing enough as it is.

**Comment by anastasiamac** [comment]
@Meai1 
In most cases where abbreviations where used we were trying to use available space efficiently.

However, if it does not look acceptable for you, please file a bug report on launchpad and provide the output that you wish to be changed. Having both the output that you are currently getting and the output that you expected to see would be helpful.
We track Juju issues on launchpad - https://bugs.launchpad.net/juju

Thank you!
