### ISSUE TITLE
Removing application does not work via gui button or cli

### ISSUE THREAD

**Issue by Meai1** [juju/juju#6825]
Only this worked, as described on irc by bdx:

```
`juju run --machine <#> "sudo rm -rf /var/lib/juju/agents/unit-<application-name>-<application-number>"
`juju resolved cassandra/<#> && juju remove-application cassandra`
```

Please wrap that in a "force remove" button and cli option.. would be good.

**Comment by anastasiamac** [comment]
@Meai1 
We track Juju issues on launchpad - https://bugs.launchpad.net/juju

I have filed this as https://bugs.launchpad.net/juju/+bug/1657657

Thank you for your report!
