### ISSUE TITLE
Juju delete SecurityGroup failed,Indicate that Unsupported request Content-Type

### ISSUE THREAD

**Issue by zhoutiekui** [juju/juju#6834]
The error is :
 juju.provider.openstack firewaller.go:282 deleting security group "juju-356b06b8-0655-475f-8d88-6705a3c07615-ab27e506-f78f-4183-827f-1530d8727bde"

I get the API Calling record as below:

DELETE /v2/a005c8d039ee4980a919cfc6cffd020a/os-security-groups/41dbe1d0-9f36-40be-b8b4-97c23e0df300 HTTP/1.1
Host: ...
User-Agent: goose (0.1.0)
Accept: application/octet-stream
Content-Type: application/octet-stream
X-Auth-Token: MIIL0gYJKoZIhvcNAQcCoIILwzCCC78CAQExDTALBglghkgBZQMEAgEwggogBgkqhkiG9w0BBwGgggoRBIIKDXsidG9rZW4iOnsiaXNzdWVkX2F0IjoiMjAxNy0wMS0xOVQwNjoyNjoxNC41MTEwMDBaIiwiZXhwaXJlc19hdCI6IjIwMTctMDEtMjBUMDY6MjY6MTQuNTExMDAwWiIsIm1ldGhvZHMiOlsicGFzc3dvcmQiXSwicHJvamVjdCI6eyJuYW1lIjoiZXUtZGUiLCJpZCI6ImEwMDVjOGQwMzllZTQ5ODBhOTE5Y2ZjNmNmZmQwMjBhIiwiZG9tYWluIjp7Im5hbWUiOiJqaWFuZ3lhcXVuIiwiaWQiOiJmODgxMDFlNjEzZGM0NDBhODAwMDA4MTNkYTBhZWRjMCJ9fSwidXNlciI6eyJkb21haW4iOnsibmFtZSI6ImppYW5neWFxdW4iLCJpZCI6ImY4ODEwMWU2MTNkYzQ0MGE4MDAwMDgxM2RhMGFlZGMwIn0sImlkIjoiZGVkYTY3NmMyNWE4NGJmN2EwZWFiMGU4NWU3NmQxNGYiLCJuYW1lIjoiamlhbmd5YXF1biJ9LCJjYXRhbG9nIjpbeyJ0eXBlIjoiZG5zIiwiaWQiOiJlMDNkZWU1ZjZmMjU0ZTM0YTQwMGMwOGRjOGM3ODM0OSIsImVuZHBvaW50cyI6W3sidXJsIjoiaHR0cHM6Ly9kbnMuZXUtZGUub3RjLnQtc3lzdGVtcy5jb20iLCJyZWdpb24iOiJldS1kZSIsInJlZ2lvbl9pZCI6ImV1LWRlIiwiaW50ZXJmYWNlIjoicHVibGljIiwiaWQiOiIyMTAxOTQ0MDQwNWU0ZmQyOWM5ZmVlNzMzYTU1NGY5ZCJ9XX0seyJ0eXBlIjoiaW1hZ2UiLCJpZCI6IjdiZjg1YjA4Y2VjOTQ1NjZiMDc5MzY0MzE0OTMzMzU5IiwiZW5kcG9pbnRzIjpbeyJ1cmwiOiJodHRwczovL2ltcy5ldS1kZS5vdGMudC1zeXN0ZW1zLmNvbSIsInJlZ2lvbiI6ImV1LWRlIiwicmVnaW9uX2lkIjoiZXUtZGUiLCJpbnRlcmZhY2UiOiJwdWJsaWMiLCJpZCI6IjJkNDNhYTE5ODE4YTQ5ODM5MGI3NGRlNjJmOGE5NTE0In1dfSx7InR5cGUiOiJuZXR3b3JrIiwiaWQiOiIwYTQyNTVjMmIyM2U0YzQ3OTg5YmRlODljNGZkZmE5NyIsImVuZHBvaW50cyI6W3sidXJsIjoiaHR0cHM6Ly92cGMuZXUtZGUub3RjLnQtc3lzdGVtcy5jb20iLCJyZWdpb24iOiJldS1kZSIsInJlZ2lvbl9pZCI6ImV1LWRlIiwiaW50ZXJmYWNlIjoicHVibGljIiwiaWQiOiI0MDJhNjhjNjNiMjA0MjRiOWE5NWZiM2I5ODk2MGI1ZiJ9XX0seyJ0eXBlIjoib3JjaGVzdHJhdGlvbiIsImlkIjoiMjRjMjc3MTlkOGM4NDc1ODk5YTYwMWVkZDdlYzdiMTMiLCJlbmRwb2ludHMiOlt7InVybCI6Imh0dHBzOi8vcnRzLmV1LWRlLm90Yy50LXN5c3RlbXMuY29tL3YxL2EwMDVjOGQwMzllZTQ5ODBhOTE5Y2ZjNmNmZmQwMjBhIiwicmVnaW9uIjoiZXUtZGUiLCJyZWdpb25faWQiOiJldS1kZSIsImludGVyZmFjZSI6InB1YmxpYyIsImlkIjoiNDVmODJjNDdjNDE3NDdmZmFkYWEwMGFlMmVhZWExYWUifV19LHsidHlwZSI6InZvbHVtZXYyIiwiaWQiOiIyNDJmYzRmNjE5NTg0YTQ3ODRjNzBiNzdkNGYxMzYyMyIsImVuZHBvaW50cyI6W3sidXJsIjoiaHR0cHM6Ly9ldnMuZXUtZGUub3RjLnQtc3lzdGVtcy5jb20vdjIvYTAwNWM4ZDAzOWVlNDk4MGE5MTljZmM2Y2ZmZDAyMGEiLCJyZWdpb24iOiJldS1kZSIsInJlZ2lvbl9pZCI6ImV1LWRlIiwiaW50ZXJmYWNlIjoicHVibGljIiwiaWQiOiI3OTIxNTJkNmM5OTQ0YzY1YWM4YzI4NDk5OWU3MmQ3NyJ9XX0seyJ0eXBlIjoiY29tcHV0ZSIsImlkIjoiODc1ZWUwMjkyMDYxNGIzNmI4YTY4MDZhNTRkYzQ1M2YiLCJlbmRwb2ludHMiOlt7InVybCI6Imh0dHBzOi8vZWNzLmV1LWRlLm90Yy50LXN5c3RlbXMuY29tL3YyL2EwMDVjOGQwMzllZTQ5ODBhOTE5Y2ZjNmNmZmQwMjBhIiwicmVnaW9uIjoiZXUtZGUiLCJyZWdpb25faWQiOiJldS1kZSIsImludGVyZmFjZSI6InB1YmxpYyIsImlkIjoiOTY3ZTAwNjYyZGVjNGQ1ZGE4ZjllZjc3YjE5ZTZlZWQifV19LHsidHlwZSI6InZvbHVtZSIsImlkIjoiODBjNWQyYzRiM2MwNDVhOGJkMDQ0NzMxODZhNTJlYzQiLCJlbmRwb2ludHMiOlt7InVybCI6Imh0dHBzOi8vZXZzLmV1LWRlLm90Yy50LXN5c3RlbXMuY29tL3YyL2EwMDVjOGQwMzllZTQ5ODBhOTE5Y2ZjNmNmZmQwMjBhIiwicmVnaW9uIjoiZXUtZGUiLCJyZWdpb25faWQiOiJldS1kZSIsImludGVyZmFjZSI6InB1YmxpYyIsImlkIjoiYzBjMGY2YTEyYzdlNGIzOTkxZTU5ZmE0OTVmYjQ5MzMifV19LHsidHlwZSI6ImlkZW50aXR5IiwiaWQiOiIxMTI5NDQzMDBkNzQ0MjM4ODViMDBjYmVlNGEwMTkyNSIsIm5hbWUiOiJrZXlzdG9uZSIsImVuZHBvaW50cyI6W3sidXJsIjoiaHR0cHM6Ly9pYW0uZXUtZGUub3RjLnQtc3lzdGVtcy5jb20vdjMiLCJyZWdpb24iOiIqIiwicmVnaW9uX2lkIjoiKiIsImludGVyZmFjZSI6InB1YmxpYyIsImlkIjoiNjVhNjM5MTE2OTIzNDA3MDlmZWZmYzQwZDkyZjNhODUifV19XSwicm9sZXMiOlt7Im5hbWUiOiJ0ZV9hZ2VuY3kiLCJpZCI6IjhmNTc5ODA4ZTg0NDQwNjE4YTI5ZTEyZWM3ZGM4NWJiIn0seyJuYW1lIjoidGVfYWRtaW4iLCJpZCI6ImQzNzZmNzhlMjNiODQwZDFiYmRiZDVhMmNiNTI5Yzk3In0seyJpZCI6IjAiLCJuYW1lIjoib3BfZ2F0ZWRfcmRzX3BnIn0seyJpZCI6IjAiLCJuYW1lIjoib3BfZ2F0ZWRfbXJzbW9kZSJ9LHsiaWQiOiIwIiwibmFtZSI6Im9wX2dhdGVkX21ycyJ9LHsiaWQiOiIwIiwibmFtZSI6Im9wX2dhdGVkXzAwMiJ9XX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATANBgkqhkiG9w0BAQEFAASCAQAxmLxZgoLeOf-gEoQJiOpYj4Y-CQBJYr0eyh6vZZVzBTbjZ8ion3IZPIuuIpT2kOV84nCrj4NHBilzSgPNg2urprlDLJ3NFriXj31tMG0GYxb-cN1AcSsLW2JoHS7p4KvEQWeDz5+92gM9kTkCOsSH3wodnXafXUV5zzT1gZglvinAzRWCt-No6VVZ1NB8Dy+J8u1qLmzlFhg0HpwXyv+Ky+Chds5gnQvIxiZjUhnYvDeuLdtFDPuOwt55mQIU9R899czBMBYzDU2eIWKqed8cvZes7PZaMQxuP1FmuG9lf-Z17GSdqmYzJltUR9KU+wgFVm72aa0r-ngS6AvCMZxu
Accept-Encoding: gzip
Connection: close

HTTP/1.1 400 Bad Request
Server: Web Server
Date: Thu, 19 Jan 2017 06:29:58 GMT
Content-Type: application/json
Content-Length: 68
Connection: close
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
X-Compute-Request-Id: req-fbdb7339-a622-4074-9799-fd674661368e
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block

{"badRequest": {"message": "Unsupported Content-Type", "code": 400}}

**Comment by anastasiamac** [comment]
@zhoutiekui 
We track out issues in launchpad - https://bugs.launchpad.net/juju

Please specify what version of Juju you were using.

This looks like https://bugs.launchpad.net/juju/+bug/1642300. If you disagree, please open another bug in launchpad. 

Thank you for the report!

**Comment by zhoutiekui** [comment]
@anastasiamac 
Hi,I have report the bug to the lauchpad, https://bugs.launchpad.net/juju/+bug/1657666, thanks.
