### ISSUE TITLE
add ability to specify LXD https port

### ISSUE THREAD

**Issue by hamsterksu** [juju/juju#6856]
Hi,

Seems lxd provider setups default (8443) for host lxd 

https://github.com/juju/juju/blob/6cf1bc9d917a4c56d0034fd6e0d6f394d6eddb6e/tools/lxdclient/utils.go#L75

Please add ability to specify PORT in bootstrap config 

Thanks,

**Comment by reedobrien** [comment]
@hamsterksu  We track issues on launchpad: https://bugs.launchpad.net/juju 

I've added the details of this issue there: https://bugs.launchpad.net/juju/+bug/1658826

**Comment by reedobrien** [comment]
@anastasiamac can you close this?
