### ISSUE TITLE
Any interest in a JuJu provider that runs Terraform?

### ISSUE THREAD

**Issue by tintoy** [juju/juju#6876]
Hi. Just asking to see if it's worth looking into. Pretty sure it's doable, since I did something similar for Docker Machine a while back:

https://github.com/tintoy/docker-machine-driver-terraform

PS. Launchpad looked like it was for bugs only but I'm happy to repost this there if it's a more appropriate forum.

**Comment by anastasiamac** [comment]
Thank you for asking!

We prefer to track anything Juju 2.x related on launchpad: https://bugs.launchpad.net/juju

I've created https://bugs.launchpad.net/juju/+bug/1661157 as a Wishlist item.
