### ISSUE TITLE
juju can't install because of an issue with Google Compute Engine

### ISSUE THREAD

**Issue by Metztli** [juju/juju#7107]
We track issues in launchpad.

## Juju 2.x issue or future work

Please file an issue against 
 [https://bugs.launchpad.net/juju](https://bugs.launchpad.net/juju)
go get -d -v github.com/juju/juju/...

go version
go version go1.7.4 linux/amd64

go install -v github.com/juju/juju/...

github.com/juju/cmd
gopkg.in/macaroon-bakery.v1/httpbakery
github.com/juju/juju/provider/gce/google
github.com/juju/juju/generate/winuserdata
github.com/juju/juju/scripts/ssh-keycheck
# github.com/juju/cmd
src/github.com/juju/cmd/logging.go:38: undefined: loggo.NewColorWriter
src/github.com/juju/cmd/logging.go:149: undefined: loggo.SeverityColor
# gopkg.in/macaroon-bakery.v1/httpbakery
src/gopkg.in/macaroon-bakery.v1/httpbakery/error.go:31: undefined: httprequest.ErrorMapper
src/gopkg.in/macaroon-bakery.v1/httpbakery/visitor.go:112: cannot use req (type *http.Request) as type "golang.org/x/net/context".Context in argument to httpReqClient.Do:
        *http.Request does not implement "golang.org/x/net/context".Context (missing Deadline method)
# github.com/juju/juju/provider/gce/google
src/github.com/juju/juju/provider/gce/google/conn_instance.go:185: invalid operation: existingItem.Value == value (mismatched types *string and string)
src/github.com/juju/juju/provider/gce/google/conn_instance.go:189: cannot use value (type string) as type *string in field value
src/github.com/juju/juju/provider/gce/google/conn_instance.go:191: cannot use value (type string) as type *string in assignment
src/github.com/juju/juju/provider/gce/google/instance.go:185: cannot use value (type string) as type *string in field value
src/github.com/juju/juju/provider/gce/google/instance.go:201: cannot use item.Value (type *string) as type string in assignment
src/github.com/juju/juju/provider/gce/google/raw.go:311: cannot use rc.Service.ZoneOperations.Get(projectID, zoneName, op.Name) (type *compute.ZoneOperationsGetCall) as type opDoer in assignment:
        *compute.ZoneOperationsGetCall does not implement opDoer (wrong type for Do method)
                have Do(...googleapi.CallOption) (*compute.Operation, error)
                want Do() (*compute.Operation, error)
src/github.com/juju/juju/provider/gce/google/raw.go:314: cannot use rc.Service.RegionOperations.Get(projectID, region, op.Name) (type *compute.RegionOperationsGetCall) as type opDoer in assignment:
        *compute.RegionOperationsGetCall does not implement opDoer (wrong type for Do method)
                have Do(...googleapi.CallOption) (*compute.Operation, error)
                want Do() (*compute.Operation, error)
src/github.com/juju/juju/provider/gce/google/raw.go:316: cannot use rc.Service.GlobalOperations.Get(projectID, op.Name) (type *compute.GlobalOperationsGetCall) as type opDoer in assignment:
        *compute.GlobalOperationsGetCall does not implement opDoer (wrong type for Do method)
                have Do(...googleapi.CallOption) (*compute.Operation, error)
                want Do() (*compute.Operation, error)
---------------------------------------------------
cd src/github.com/juju/juju
 make install-dependencies

go version
go version go1.6.1 gccgo (Debian 6.3.0-8) 6.3.0 20170221 linux/amd64

 go install -v github.com/juju/juju/...
[error]
src/github.com/juju/juju/provider/gce/google/conn_instance.go:185:47: error: incompatible types in binary expression
  if existingItem != nil && existingItem.Value == value {
                                               ^
src/github.com/juju/juju/provider/gce/google/conn_instance.go:189:83: error: incompatible type for field 2 in struct construction
   metadata.Items = append(metadata.Items, &compute.MetadataItems{Key: key, Value: value})
                                                                                   ^
src/github.com/juju/juju/provider/gce/google/conn_instance.go:191:22: error: incompatible types in assignment
   existingItem.Value = value
                      ^
src/github.com/juju/juju/provider/gce/google/instance.go:185:11: error: incompatible type for field 2 in struct construction
    Value: value,
           ^
src/github.com/juju/juju/provider/gce/google/instance.go:201:20: error: incompatible types in assignment
   result[item.Key] = item.Value
                    ^
src/github.com/juju/juju/provider/gce/google/raw.go:311:8: error: incompatible types in assignment (incompatible type for method ‘Do’ (different number of parameters))
   call = rc.ZoneOperations.Get(projectID, zoneName, op.Name)
        ^
src/github.com/juju/juju/provider/gce/google/raw.go:314:8: error: incompatible types in assignment (incompatible type for method ‘Do’ (different number of parameters))
   call = rc.RegionOperations.Get(projectID, region, op.Name)
        ^
src/github.com/juju/juju/provider/gce/google/raw.go:316:8: error: incompatible types in assignment (incompatible type for method ‘Do’ (different number of parameters))
   call = rc.GlobalOperations.Get(projectID, op.Name)

## Juju 1.x issue

Please file an issue against 
 [https://bugs.launchpad.net/juju-core](https://bugs.launchpad.net/juju-core)

# Thank you for finding a Juju Issue!

**Comment by anastasiamac** [comment]
Before running 'go install -v github.com/juju/juju/...', you need to ensure that you have all build and runtime dependencies. The best way to do it is via running 
go get github.com/rogpeppe/godeps
cd $GOPATH/src/github.com/juju/juju
godeps -u dependencies.tsv

We are working on improving this part of our documentation. Best version at this stage is at https://github.com/juju/juju/blob/2.1/README.md which will point you to https://github.com/juju/juju/blob/2.1/CONTRIBUTING.md#dependency-management. Please follow these steps.

This version will be promoted to juju/juju staging.
