### ISSUE TITLE
Deadlinks

### ISSUE THREAD

**Issue by rauhs** [juju/juju#7154]
The first link in the readme is a deadlink. ( http://jujucharms.com/charms )

Also "How it works" ( https://jujucharms.com/how-it-works ) -> "Learn more about writing charms ›" deadlinks.

**Comment by wallyworld** [comment]
Thanks for reporting the issue.

There is a separate repo for Juju docs - https://github.com/juju/docs
I'll close the issue here and open a new one in the doc repo.
https://github.com/juju/docs/issues/1752

**Comment by pmahnke** [comment]
@wallyworld I think @rauhs means - [this readme page](https://github.com/juju/juju/blob/staging/README.md) not the docs?

and 

this [how it works page](https://github.com/CanonicalLtd/blues_browser/blob/c0019afb7d1f6c67510a29a1e38bc3538e6e49d9/jaas_storefront/templates/static_pages/how-it-works.jinja2)

**Comment by matthewhelmke** [comment]
Agreed @pmahnke . This does not apply to the [docs readme](https://github.com/juju/docs/blob/master/README.md).
