### ISSUE TITLE
`juju config` showing wrong defaults 

### ISSUE THREAD

**Issue by wurde** [juju/juju#7359]
Running `juju config` for config with boolean values are showing 'true' when the actual default is 'false'. It looks like juju is making an assumption that it should be making at all. The defaults are explicitly set in the config.yml file.

  exposed:
    default: true
    description: Set service port(s) open or closed to remote traffic.
    type: boolean
    value: false

**Comment by howbazaar** [comment]
We generally track issues on Launchpad. But this is just confusing rather than wrong. The default value here is just saying whether or not the value specified is the default value or not, not the actual value of the default.
