### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [juju/juju#7685]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (Gorm or Xorm or any popular DBs).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current permisssion system [here](https://github.com/juju/juju/blob/develop/permission/access.go). Let me know if there's any question:) Thanks.

**Comment by anastasiamac** [comment]
We track issues and wishlist items in launchpad.

## Juju 2.x issue or future work

Please file an issue against 
 [https://bugs.launchpad.net/juju](https://bugs.launchpad.net/juju)


## Juju 1.x issue

Please file an issue against 
 [https://bugs.launchpad.net/juju-core](https://bugs.launchpad.net/juju-core)

Please close this issue on github - Juju team is un-likely to see it not track it here.

**Comment by hsluoyz** [comment]
Thanks!
