### ISSUE TITLE
getting "juju.worker.diskmanager error" after recovery

### ISSUE THREAD

**Issue by michaeleino** [juju/juju#8403]
I got the below after I do recover one machine at a time...

the scenario..
I enabled HA for 3 nodes, dropped one machine and recovered it... after recovery, dropped another machine and recovered it..
What should I check further!?

juju 2.3.2-xenial-amd64
Ubuntu 16.04.3 LTS
MAAS Version: 2.3.0-6434-gd354690-0ubuntu1~16.04.1

machine-1: 11:15:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:15:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:15:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:15:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:16:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:16:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:16:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:16:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:17:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:17:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:17:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:17:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:18:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:18:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:18:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:18:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:19:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:19:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:19:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:19:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:20:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:20:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:20:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:20:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:21:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:21:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:21:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:21:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:22:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:22:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:22:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:22:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:23:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:23:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:23:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:23:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:24:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:24:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:24:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:24:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:25:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:25:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:25:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:25:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:26:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:26:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:26:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:26:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:27:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:27:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:27:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:27:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:28:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:28:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:28:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:28:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:29:06 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:29:08 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-1: 11:29:36 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2
machine-18: 11:29:38 ERROR juju.worker.diskmanager error getting hardware info for "cciss/c0d0" from sysfs: udevadm failed: exit status 2

**Comment by anastasiamac** [comment]
Thank you for bringing this up.

We track issues on launchpad at - https://bugs.launchpad.net/juju

Closing this report in favor of https://bugs.launchpad.net/juju/+bug/1750683

**Comment by nskaggs** [comment]
@michaeleino Are you able to comment on the launchpad bug linked? It would be helpful to clarify which machine is giving this error (the one you dropped or ?). Also more logs would be useful.

**Comment by michaeleino** [comment]
@nskaggs Yes, i can comment there,,, but I have dropped everything and started a fresh installation for production, I can't drop machines now to reproduce this issue :(

For the error, yup the each dropped machine emits these errors..
NOTE: i'm recovering the on the same physical dropped machine.
i.e I release the machine from MAAS web interface, then I do trigger "juju enable-ha --to dropped.machine"
