### ISSUE TITLE
Bootstraping isn't dealing well with whrong credentials

### ISSUE THREAD

**Issue by revagomes** [juju/juju#848]
After trying to set up a new aws environment I had a typo in my credentials so after getting error before the juju bootstrap I fixed the environment settings but because of the my-new-enviroment.jenv was already there I was not able to bootstrap it again without deleting the old one.

Here goes the error message:

ERROR AWS was not able to validate the provided access credentials (AuthFailure)
vagrant@cf-juju:~/.juju$ juju bootstrap
WARNING ignoring environments.yaml: using bootstrap config in file "/home/vagrant/.juju/environments/my-new-enviroment.jenv"
ERROR cannot determine if environment is already bootstrapped.: The AWS Access Key Id you provided does not exist in our records.

**Comment by anastasiamac** [comment]
There has been a lot re-work in the area - Juju 2.0 offers a completely different experience with bootstrap and credentials.
If you need to file a bug, please visit https://bugs.launchpad.net/juju-core/
