### ISSUE TITLE
"juju status" is showing an error,  ERROR dial tcp 10.39.183.235:17070: i/o timeout

### ISSUE THREAD

**Issue by usama2490** [juju/juju#9258]
We track issues in launchpad.

## Juju 2.x issue or future work

Please file an issue against 
 [https://bugs.launchpad.net/juju](https://bugs.launchpad.net/juju)

## Juju 1.x issue

Please file an issue against 
 [https://bugs.launchpad.net/juju-core](https://bugs.launchpad.net/juju-core)

# Thank you for finding a Juju Issue!

**Comment by SimonRichardson** [comment]
@usama2490 can you file a bug against https://bugs.launchpad.net/juju
